### PR TITLE
fix(client): prefix reuse

### LINKED ISSUE #7367: Prefix `ClientInitState` reuse in client DB
https://github.com/fedimint/fedimint/blob/601ad98a4672da1aa3fdc034cf0c0a5be9d9871a/fedimint-client/src/db.rs#L342-L346

https://github.com/fedimint/fedimint/blob/601ad98a4672da1aa3fdc034cf0c0a5be9d9871a/fedimint-client/src/db.rs#L359-L363

https://github.com/fedimint/fedimint/blob/601ad98a4672da1aa3fdc034cf0c0a5be9d9871a/fedimint-client/src/db.rs#L389-L393

Great find @maan2003

### PR DESCRIPTION
**Pull request by dpc**
Fix #7367

Tested manually in `devimint-env`, by doing a restore on an old version, then switching to new version:

```
2025-05-01T18:06:07.960066Z  INFO fm::db: Migrating module... kind="fedimint-client" current_db_version=DatabaseVersion(3) target_db_version=DatabaseVersion(4)
2025-05-01T18:06:07.960132Z DEBUG fm::client::db: Migrating old ClientModuleRecovery key module_id=0
2025-05-01T18:06:07.960281Z DEBUG fm::client::db: Migrating old ClientModuleRecovery key module_id=1
2025-05-01T18:06:07.960384Z DEBUG fm::client::db: Migrating old ClientModuleRecovery key module_id=2
2025-05-01T18:06:07.960461Z DEBUG fm::client::db: Migrating old ClientModuleRecovery key module_id=3
2025-05-01T18:06:07.960537Z DEBUG fm::client::db: Migrating old ClientModuleRecovery key module_id=4
2025-05-01T18:06:07.960611Z DEBUG fm::client::db: No more ClientModuleRecovery keys found for migartion module_id=5
2025-05-01T18:06:07.960684Z DEBUG fm::db: DB Version kind="fedimint-client" db_version=DatabaseVersion(4)
2025-05-01T18:06:07.962773Z DEBUG fedimint_client::client: Detected configuration for unsupported module id: 5, kind: unknown
```

```
> fedimint-dbtool --database-dir $FM_CLIENT_DIR/client.db list --prefix "31"
31 01020100
> fedimint-dbtool --database-dir $FM_CLIENT_DIR/client.db list --prefix "40"
4000 0101
4001 0101
4002 0101
4003 0101
4004 0101
```

### CODE REVIEW

File: fedimint-client/src/client/builder.rs [hunk 1]
```diff
@@ -191,7 +191,13 @@ impl ClientBuilder {
         self.meta_service = meta_service;
     }
 
-    async fn migrate_database(&self, db: &Database) -> anyhow::Result<()> {
```
Comment (dpc) [inline fedimint-client/src/client/builder.rs:194]: Confusing name.

File: fedimint-client/src/db.rs [hunk 2]
```diff
@@ -350,31 +351,11 @@ impl_db_lookup!(
     query_prefix = ClientInitStatePrefix
 );
 
-#[derive(Debug, Encodable, Decodable, Serialize)]
```
Comment (dpc) [inline fedimint-client/src/db.rs:353]: Wasn't used for anything.

File: fedimint-client/src/db.rs [hunk 3]
```diff
@@ -642,9 +636,41 @@ pub fn get_core_client_database_migrations()
...
+                Ok(())
+            })
+        }),
+    );
     migrations
 }
 
+/// Apply core client database migrations
+///
+/// TODO: This should be private.
```
Comment (dpc) [inline fedimint-client/src/db.rs:673]: We call it manually from `fedimint-testing`, so can't fix it ATM.

**Comment by bradleystachurski** [comment]
@dpc Do we need to consider any backports?

File: fedimint-client/src/db.rs [hunk 4]
```diff
@@ -642,9 +636,41 @@ pub fn get_core_client_database_migrations()
...
     );
+
+    // Fix #7367
+    migrations.insert(
+        DatabaseVersion(3),
+        Box::new(|mut ctx: fedimint_core::db::DbMigrationFnContext<'_, _>| {
+            Box::pin(async move {
+                let mut dbtx = ctx.dbtx();
+
+                for module_id in 0..u16::MAX {
```
Comment (elsirion) [inline fedimint-client/src/db.rs:647]: Prefix query wouldn't work due to the prefix-sharing, so this seems like a reasonable approach. Alternative: use raw prefix querying and length checks before decoding.

**Review by elsirion — APPROVED** [review]
Looks good.

Re backporting:
* *Pro*: if we need to backport another DB migration this would make it much easier (not having to worry about divergent DB versions on branches)
* *Con*: this is really just a cleanup to make the code easier to understand, no observable bugs were caused by this

**Comment by bradleystachurski** [comment]
Dang, looks like this failed due to the macos dev shell timeout. I'll open a PR to bump from 60 to 90 minutes.

https://github.com/fedimint/fedimint/actions/runs/14782856243/job/41505395101

Screenshot_20250501_163406

**Comment by dpc** [comment]
@bradleystachurski I think:

image

Posted a thread on #infra
