### PR TITLE
fix: make code version string a valid SemVer version number

### LINKED ISSUE #6487: cli tests: failed version parsing with vendor suffix
semver version parsing is failing with vendor suffix is failing

https://github.com/fedimint/fedimint/blob/b3fcaa2fda1565004d9e377ed74d885b07b081f7/devimint/src/tests.rs#L979-L982

because it is not semver compatible

https://github.com/fedimint/fedimint/blob/b3fcaa2fda1565004d9e377ed74d885b07b081f7/fedimintd/src/fedimintd.rs#L266-L270

but even after fixing it, versions in both commands are different

```
bash-5.2$ fedimint-cli dev peer-version --peer-id 0
{
  "version": "0.4.4.fedi"
}
bash-5.2$ fedimintd --version
fedimintd 0.4.4 
```

### PR DESCRIPTION
**Pull request by elsirion**
Fixes #6487

### CODE REVIEW

File: fedimintd/src/fedimintd.rs [hunk 1]
```diff
@@ -265,7 +265,7 @@ impl Fedimintd {
             code_version_hash: code_version_hash.to_owned(),
             code_version_str: code_version_vendor_suffix.map_or_else(
                 || fedimint_version.to_string(),
-                |suffix| format!("{fedimint_version}.{suffix}"),
+                |suffix| format!("{fedimint_version}-{suffix}"),
```
Comment (dpc) [inline fedimintd/src/fedimintd.rs:268]: If we want this to pass semver, then we should probably use a `+` which means "build" which matches our meaning better than `-` "prerelease".

Comment (elsirion) [reply fedimintd/src/fedimintd.rs]: Good point, otherwise it might be colliding with RCs

**Review by dpc — APPROVED** [review]
