### PR TITLE
Graceful shutdown fixes

### LINKED ISSUE #1418: Does not terminate (hangs) on panic
On error I've spotted in https://github.com/fedimint/fedimint/issues/1417#issue-1549749091 the fedimint killed all the peer connections, but then did not stop, preventing `systemd` from starting it again.

### PR DESCRIPTION
**Pull request by elsirion**
- [x] Move main task into task group
- [x] Limit time `shutdown` can take

Fixes #1418

### CODE REVIEW

File: fedimintd/src/bin/main.rs [hunk 1]
```diff
@@ -114,11 +153,6 @@ async fn main() -> anyhow::Result<()> {
     let key = get_key(opts.password, salt_path)?;
     let cfg = read_server_configs(&key, opts.data_dir.clone())?;
 
-    let local_task_set = tokio::task::LocalSet::new();
```
Comment (elsirion) [inline fedimintd/src/bin/main.rs:117]: I'm not sure what the `local_task_set` is good for. Doesn't seem to get used.

File: fedimintd/src/bin/main.rs [hunk 2]
```diff
@@ -72,7 +75,43 @@ async fn main() -> anyhow::Result<()> {
...
 
-    let mut task_group = TaskGroup::new();
+    let mut root_task_group = TaskGroup::new();
+    root_task_group.install_kill_handler();
+
+    let task_group = root_task_group.clone();
+    let (main_shutdown_tx, main_shutdown_rx) = tokio::sync::oneshot::channel::<()>();
+
+    root_task_group
+        .spawn_local("main", move |_task_handle| async move {
```
Comment (dpc) [inline fedimintd/src/bin/main.rs:85]: IIRC you can get the `TaskGroup` from the `TaskHandle` to avoid clone.

File: fedimintd/src/bin/main.rs [hunk 3]
```diff
@@ -72,7 +75,43 @@ async fn main() -> anyhow::Result<()> {
...
+            match run(opts, task_group).await {
+                Ok(()) => {
+                    info!("Shutting down");
+                }
+                Err(e) => {
+                    error!(?e, "Main task returned error, shutting down");
+                }
+            }
+
+            main_shutdown_tx
```
Comment (dpc) [inline fedimintd/src/bin/main.rs:95]: Seems like we should `task_group.shutdown();`here. (If we are out of run, we want everything else to finish).

Comment (dpc) [reply fedimintd/src/bin/main.rs:95]: So we wouldn't need  `main_shutdown_rx.await` (or that `oneshot` channel at all)` and we could just do `root_task_group.join_all().await`

File: fedimintd/src/bin/main.rs [hunk 4]
```diff
@@ -72,7 +75,43 @@ async fn main() -> anyhow::Result<()> {
...
+                .send(())
+                .expect("Could not send shutdown signal");
+        })
+        .await;
+
+    main_shutdown_rx.await.expect("Main task panicked");
+
+    root_task_group.shutdown().await;
```
Comment (dpc) [inline fedimintd/src/bin/main.rs:103]: As mentioned above  - this should be `join_all`, and we don't want limit the time out `shutdown()` (if finishes right away), but the time of `join_all` **after** `is_shutting_down` flag was set.

File: fedimintd/src/bin/main.rs (hunk 1 above)
Comment (dpc) [reply fedimintd/src/bin/main.rs:117]: Oh damn. This has something to do with `consensus` not being `Send` or something, and the fact that we need to `spawn_local` it. This was just creating some set of threads for it to run in a non-send mode(?), then "enter" it, and then check the results from it. Bleh.

File: fedimintd/src/bin/main.rs (hunk 3 above)
Comment (dpc) [reply fedimintd/src/bin/main.rs:95]: Oh... This is bad.

Possibly we should have a `while` loop there and lock, pop one, wait one it, until we don't have any more?

Comment (dpc) [reply fedimintd/src/bin/main.rs:95]: I wouldn't be surprised if this wasn't one of the root issues. Good catch.

Who wrote it? What was he thinking. :D

Comment (elsirion) [reply fedimintd/src/bin/main.rs:95]: I'll take a look tomorrow with a fresh mind. The while loop seems ok, we'd want a `VecDequeue` though to pop from the opposite side than where we push. Since we don't seem to do random access we might as well use an unbounded channel.

File: fedimintd/src/bin/main.rs (hunk 1 above)
Comment (elsirion) [reply fedimintd/src/bin/main.rs:132]: The thing is, it was never used. The only side effect was some guard that was spawned. I removed it and it didn't seem any different, but I did have to run the future in a `spawn_local` anyway.

File: fedimintd/src/bin/main.rs (hunk 2 above)
Comment (elsirion) [reply fedimintd/src/bin/main.rs:87]: I didn't find a way, but not too bad imo, just an `Arc::clone`.

File: fedimintd/src/bin/main.rs (hunk 3 above)
Comment (elsirion) [reply fedimintd/src/bin/main.rs]: I ended up making it a `VecDequeue` since the channel would have meant two member vars and a mutex around the receiver still. We should come back and refactor the `TaskGroup` such that handles can spawn, `TaskGroup` is not clone anymore and is the only thing that can `join_all`. That way consuming `self` would actually make sense (when it's just an `Arc` that can be cloned consuming self means ~nothing).

File: fedimintd/src/bin/main.rs (hunk 1 above)
Comment (elsirion) [reply fedimintd/src/bin/main.rs:132]: Lol, it does have side effects …

File: fedimint-api/src/task.rs [hunk 5]
```diff
@@ -221,12 +224,35 @@ impl TaskGroup {
...
-    pub async fn join_all(self) -> anyhow::Result<()> {
-        for (name, join) in self.inner.join.lock().await.drain(..) {
+    pub async fn join_all(self, join_timeout: Option<Duration>) -> anyhow::Result<()> {
+        while let Some((name, join)) = self.inner.join.lock().await.pop_front() {
             debug!("Waiting for {name} task to finish");
-            join.await
-                .map_err(|e| anyhow!("Thread {name} panicked with: {e}"))?;
-            debug!("{name} task finished.");
+
+            #[cfg(not(target_family = "wasm"))]
```
Comment (dpc) [inline fedimint-api/src/task.rs:231]: I would not bother with timeouts here.

Instead, I would go for:

```
impl TaskGroup {
  fn install_shutdown_deadline_terminator(&self) {
      let s_clone = self.clone();

      task::spawn(|| async { // standalone non-task-group thread
          // wait for shutdown flag being set
          while !s_clone.is_shutting_down() {
                sleep(1).await; // could be waiting for the shutting down callback or something instead of polling, but whatever
          }

          sleep(30).await; // give em some time
          

          if !s_clone.had_successful_shutdown() {
              std::process:exit(-10); // party is over
           }
      ||);
  }
}

**Comment by dpc** [comment]
Looks reasonable, but it is all kind of tricky, and I'd have to sit in front of an editor for 30 minutes - 1h to really get an educated opinion. :D

**Review by dpc — APPROVED** [review]

**Comment by elsirion** [comment]
Tested it with a panic in consensus and it works as intended: https://gist.github.com/elsirion/7aae29939c68e5d9df6c0a785add5d85

We should investigate why certain tasks are not shutting down by themselves, but that's out of scope for this PR.
