### PR TITLE
fix: use `FuturesUnordered` instead of `JoinSet`

### LINKED ISSUE #7532: Unsafe JoinSet with WASM
Dev call: @maan2003 mentioned using `tokio::spawn` won't work with wasm so we'll need to followup with additional wasm logic and testing.

_Originally posted by @bradleystachurski in https://github.com/fedimint/fedimint/pull/7437#discussion_r2162012448_

### PR DESCRIPTION
**Pull request by dpc**
JoinSet is not compat with WASM, and in this particular case `FuturesUnordered` is just fine.

Fix #7532

### CODE REVIEW

File: fedimint-api-client/src/api/iroh.rs [hunk 1]
```diff
@@ -142,32 +148,26 @@ impl IClientConnector for IrohConnector {
...
-                }
+        while let Some(result) = futures.next().await {
+            match result {
+                Ok(connection) => return Ok(connection),
                 Err(err) => {
-                    warn!(
-                        target: LOG_NET_IROH,
-                        err = %err.fmt_compact(),
-                        "Join error in iroh connection task"
-                    );
```
Comment (elsirion) [inline fedimint-api-client/src/api/iroh.rs]: Why remove the log?

**Comment by dpc** [comment]
@maan2003 In this particular case, I don't think there's any downside of using `FuturesUnordered`, so I would just do it anyway. We can still introduce `n0-future` regardless.

File: fedimint-api-client/src/api/iroh.rs (hunk 1 above)
Comment (dpc) [reply fedimint-api-client/src/api/iroh.rs]: Fixed.

**Comment by maan2003** [comment]
agreed

**Review by maan2003 — APPROVED** [review]
