### PR TITLE
make logging less noisy

### LINKED ISSUE #367: Make logging less noisy
I just played around with the client and the logging would seem scary to someone unfamiliar with the code base (many errors and warnings). We should try to investigate the errors and either fix them if something is broken or try to tone down the logging. E.g. a failed API request that can still be retried isn't really an error.

```
[nix-shell:~]$ mint-client-cli client2 reissue AQAAAAAAAABAQg8AAAAAAAoAAAAAAAAAIAAAAAAAAAB/bKuHcgzHSChmPt3BLyLbuhpqctoV6rzLddfE7TNDhjAAAAAAAAAAqUHqVivwLD++MMnCgT9lj2yv1+s41HfTHmMpqzXil6pjE5E97psGJUc1QjuBSK2l6/XMWmUQLEmXjoyJzwGt5kYBR23NrA/g+2XuPyq6zAkgAAAAAAAAAH8dBsvMZWa/dMmNKN2SiIBKQntnAQomW5wPlZjJUrprMAAAAAAAAACT5K91cd54Mvndo+td0UlgMlBdMaCJplX2mtIEayls8GwG6A11fi7uR5P3Qf/vBFrL5Klhj+2kwkQ5snhzldoUojx7pl5GkjS0aDQQ6R6mXSAAAAAAAAAAdnT42f3IypipSdHsrQwLuVm8feLWqG1s7k5wSp93SVMwAAAAAAAAALYl+7d8K/538w5bz0W4HZl0buOb+q2L2MAJFKAkxgP32cnIWEsSaT7Vq9Lag72v6nlxB6VKRGpza5sGntMCGGMS9bu3PYWyjUTsUfhstwWuIAAAAAAAAABvDdKzDQ7QG3YQ5IrkNl8dLf66PaNl8j88X49k4XElZjAAAAAAAAAAg4PViMJCfPN3k4HTgKQuvxzQahBCBT2xM7F09Zlnk3VTmpH8KE602BvzrS86lAY/6YqPWYTia3kQUAPP82hvnGAcP/V3XE3QTtbf1Yv3AvYgAAAAAAAAAG5mEYedQiTJcC9b+iu+8rhQssL2cq8yHQIe/BpMRnt9MAAAAAAAAACzVczhexAKSneNwRCzIzWmEUEHjW97cTxAW76IPc/hRNcceA/rHzLWtPBQhHSopiK0D3WVmQTp6eDvDDRqzj5joo9qLl3OeRqxRdIedwRP5CAAAAAAAAAAa/HudczkFExFocDeFCcv8Ip3kXVU4cx+1CH+OFZRpjEwAAAAAAAAAKuRlaLZ+Y7n7xYkrg9Jc7RP1kie/poznNAhM8s9pZl96GPdU1+sqQzzn/Zjsp8wslGfnZlRNHNeNZJo0eoiHg//D60zw03agQJjOKY3Q3xcIAAAAAAAAABob98hBPswiL/rffq37Zbyu7ibebN0qbuPOyNf+WNc2jAAAAAAAAAAij8itbkNeznGux3b2BdSRUNWP+c/SBLvyW/RXJghOcbyGq/LvIAZ9Z/u9T8KkDH+dQ/5FNMRletHAzuNQ6GgoDbcyx3942LgRZSY+9n8rH0gAAAAAAAAAEydemglxFmsIO14MXejLVi0zNlHa+vuIU3CWflQaJg1MAAAAAAAAAC5pIE4YCplnqG5CGhHSstIjs1LGhMsiTBWD2Z1EBkAoZzzkf1gyS7ol6cewkV7Rwk3svEeUw68mzshlMb0+z64rWWHlzWSoIT+Z/33MPoD3CAAAAAAAAAAO2vIWJQOV+w4Ry1vH+MMJh1Hh9c0QEpYfTBj3lopzcowAAAAAAAAAIZbnZh/xiOevtwDPyUJitHChk04vUcrBNqjAKVsKW/LtxzYYYEg4QjDdizbm6j9OCrQBcfu0vUhJ6MLRRV20Kn2Vmc4Ic00fqrIz+pHTT6VIAAAAAAAAAAyPfRI7/9VaDFahe7VuWAo57BCH1eLp5Yc0EOpFVQmLjAAAAAAAAAAj7iDrgpf4RFYAoLfGGp8PgDTjha4xJw1cCWdMUKtR+tVJTaY3+MglV4xTvgaj2QsHnFrSxWGE3ahGz0kQrGzv3iWGq8jo1BfGDKvYF8HZeM=
2022-08-12T08:59:41.039946Z  INFO mint_client_cli: Starting reissuance transaction coins=10000000 msat
2022-08-12T08:59:41.047629Z  WARN request{peer=0}: mint_client::api: web socket not connected, reconnecting
2022-08-12T08:59:41.048604Z  INFO request{peer=0}: jsonrpsee_client_transport::ws: Connection established to target: Target { sockaddrs: [], host: "fm.sirion.io", host_header: "fm.sirion.io:5000", _mode: Plain, path_and_query: "/" }
2022-08-12T08:59:41.087887Z ERROR minimint_api::db::rocksdb_impl: Database deleted absent element! This should not happen!
2022-08-12T08:59:41.087907Z ERROR minimint_api::db::rocksdb_impl: Database deleted absent element! This should not happen!
2022-08-12T08:59:41.087910Z ERROR minimint_api::db::rocksdb_impl: Database deleted absent element! This should not happen!
2022-08-12T08:59:41.087914Z ERROR minimint_api::db::rocksdb_impl: Database deleted absent element! This should not happen!
2022-08-12T08:59:41.087917Z ERROR minimint_api::db::rocksdb_impl: Database deleted absent element! This should not happen!
2022-08-12T08:59:41.087921Z ERROR minimint_api::db::rocksdb_impl: Database deleted absent element! This should not happen!
2022-08-12T08:59:41.087924Z ERROR minimint_api::db::rocksdb_impl: Database deleted absent element! This should not happen!
2022-08-12T08:59:41.087928Z ERROR minimint_api::db::rocksdb_impl: Database deleted absent element! This should not happen!
2022-08-12T08:59:41.087931Z ERROR minimint_api::db::rocksdb_impl: Database deleted absent element! This should not happen!
2022-08-12T08:59:41.087934Z ERROR minimint_api::db::rocksdb_impl: Database deleted absent element! This should not happen!
2022-08-12T08:59:41.088045Z  INFO mint_client_cli: Started reissuance, please fetch the result later id=9906a5cdc9e78f21849b93407d5d9e0080c2c1eefaf57da0d952796b7807440d:0
2022-08-12T08:59:41.129239Z  WARN jsonrpsee_core::client::async_client: Custom("[backend]: frontend dropped; terminate client")

[nix-shell:~]$ mint-client-cli client2 fetch
2022-08-12T08:59:46.465415Z  WARN request{peer=0}: mint_client::api: web socket not connected, reconnecting
2022-08-12T08:59:46.466482Z  INFO request{peer=0}: jsonrpsee_client_transport::ws: Connection established to target: Target { sockaddrs: [], host: "fm.sirion.io", host_header: "fm.sirion.io:5000", _mode: Plain, path_and_query: "/" }
2022-08-12T08:59:46.508587Z  INFO mint_client_cli: Fetched coins issuance=9906a5cdc9e78f21849b93407d5d9e0080c2c1eefaf57da0d952796b7807440d
2022-08-12T08:59:46.527896Z  WARN jsonrpsee_core::client::async_client: Custom("[backend]: frontend dropped; terminate client")

[nix-shell:~]$ mint-client-cli client2 info
We own 10 coins with a total value of 10000000 msat
We own 10 coins of denomination 1000000 msat

[nix-shell:~]$ mint-client-cli client2 ln-pay lntbs420n1p30v9fqsp5el2676mxjgzsqzrp0qk4xsdx0996ap9ssn6gmxs8ztf5euu9eyyspp5qllxdet5s927h0w0d0rxfeemwez0ck5klqzzh9epzjut90awndsqdrv2pskjepqw3hjqer9d4hjq2z0wfjx2u3qf9zr5grrwfhhwerxw4hxgttpwpc97veng96n242ywdg9wmj4fs65w4j58pcnzkt2dam8wwpnfv5sxqzurcqp29qyysgqlm5xs7c24hdek9m0jjunvnsfzpup3zcz4jldmml27wmeuu52wd45eturyylqhxkjux65jd0utsasd6njct7338kk3awkych3f6qeqaqphzzkdf
2022-08-12T09:00:00.308867Z  WARN request{peer=0}: mint_client::api: web socket not connected, reconnecting
2022-08-12T09:00:00.310195Z  INFO request{peer=0}: jsonrpsee_client_transport::ws: Connection established to target: Target { sockaddrs: [], host: "fm.sirion.io", host_header: "fm.sirion.io:5000", _mode: Plain, path_and_query: "/" }
2022-08-12T09:00:00.356200Z ERROR request{peer=0}: mint_client::api: error=RPC call failed: ErrorObject { code: ServerError(404), message: "transaction not found", data: None }
2022-08-12T09:00:01.371777Z  INFO mint_client_cli: Funded outgoing contract, notifying gateway contract_id=8b5507f8a6bc1a85654b19ce80fe6c8a9919513641a5593d665233615d41b561
2022-08-12T09:00:03.553726Z  WARN jsonrpsee_core::client::async_client: Custom("[backend]: frontend dropped; terminate client")
```

### PR DESCRIPTION
**Pull request by jkitman**
Fixes #367

Note the `jsonrpsee_core` warnings could be suppressed through the logging level if necessary or maybe by running clientd instead of starting and shutting down the cli.

### CODE REVIEW

**Review by elsirion — APPROVED** [review]
Thx! Quite a QoL improvement :laughing:

File: client/client-lib/src/transaction.rs [hunk 1]
```diff
@@ -142,7 +142,8 @@ impl TransactionBuilder {
         // move input coins to pending state, awaiting a transaction
         if !self.input_coins.coins.is_empty() {
             batch.append_from_iter(self.input_coins.iter().map(|(amount, coin)| {
-                BatchItem::delete(CoinKey {
+                // maybe_delete because coins might have been received from another user directly
+                BatchItem::maybe_delete(CoinKey {
```
Comment (justinmoon) [inline client/client-lib/src/transaction.rs:146]: Is this the one that always complained about deleted items being deleted again? That one was sooo annoying!

Comment (jkitman) [reply client/client-lib/src/transaction.rs:146]: Yep :)
