### PR TITLE
Instead of erroring, retry until bitcoind returns a successful response

### LINKED ISSUE #37: Wallet Module Error Tolerance
How tolerant does the wallet module need to be relative to input errors and RPC errors of all kinds? There are many `expect` calls throughout the code. Do we prefer crashes or are these temporary measures to move development forward?

### PR DESCRIPTION
**Pull request by jkitman**
Instead of crashing when bitcoind is unavailable this will retry the requests forever, blocking the current thread and logging the error.  Tested manually.

We should eventually have a way to notify users via the server UI.

Fixes #37

### CODE REVIEW

File: fedimint-bitcoind/src/lib.rs [hunk 1]
```diff
@@ -66,17 +66,15 @@ dyn_newtype_define! {
...
     task_handle: TaskHandle,
 }
 
 impl<C> RetryClient<C> {
     pub fn new(inner: C, task_handle: TaskHandle) -> Self {
         Self {
             inner,
-            max_retries: 10,
-            base_sleep: Duration::from_millis(10),
+            sleep: Duration::from_millis(100),
```
Comment (elsirion) [inline fedimint-bitcoind/src/lib.rs:77]: We should still do some sort of back-off (exponential with an upper bound?).

Instead of failing we could just stop increasing the wait time after `max_retries`.

**Review by elsirion — CHANGES_REQUESTED** [review]
As-is this is a DoS against bitcoind. We could just increase the time to wait before retrying, but that would increase latency when there's just a random failure (why I introduced the `RetryClient` in the first place).

**Comment by dpc** [comment]
> As-is this is a DoS against bitcoind. 


Exponential backoff is only ever really necessary in cases where there is potentially orders of magnitude more clients than servers.

[In `rust-bitcoin-indexer` I have a thread pool hammering bitcoind via rpc for block data](https://github.com/dpc/rust-bitcoin-indexer/blob/8a9b041928a7c8c4d267a810f582cf3906ed511b/src/node/prefetcher.rs#L162) with a fixed delay - never seen any issues with it. By default bitcoind starts `num_cpus` number of threads to handle requests, IIRC. Under too many request at the same it just disconnects new connections.

**Comment by elsirion** [comment]
My main fear is that on slow machines (e.g. with only one core) this could significantly slow down the operation that is blocking bitcoind from answering RPC requests at the moment, so we are kinda shooting ourselves into the foot. Maybe that's a misconception on my side.

My proposal would be wait a *shorter* time at the beginning to reduce best-case latency (e.g. 10ms) and then exponentially back-off to a max of 1s or so wait time between re-tries, giving bitcoind some breathing room if it can't answer because it's processing a block (which can take quite some time on slow HW).

**Comment by dpc** [comment]
Exponential back-off won't hurt, that's for sure.

IIRC `bitcoind` has a threadpool (`rpcthreads`- default 4) for processing requests and a request queue (with lenght set by `rpcworkqueue`). If node is overloaded the connections are still accepted but just sit in the queue. If the queue is overflowing new requests will be just rejected (which is very lightweight operation).

So the overload protection should be done on `bitcoind` side, and we don't really have much control over it here. On a very low power machine, the user should probably lower the `rpcthreads` and `bitcoind` will just queue everyone and process as fast it can.

**Comment by jkitman** [comment]
So it sounds like we can just keep this loop every 10ms for now?  Let bitcoind throttle the requests by blocking?

**Review by elsirion — APPROVED** [review]
Let's just keep in mind that could be a cause of high CPU usage when bitcoind is down. Let's fix it if it turns out to be an actual problem.
