### PR TITLE
better DKG failures if modules are missing 

### LINKED ISSUE #2538: Fail if params for module config gen are missing
Currently the module is skipped, which is unexpected.

### PR DESCRIPTION
**Pull request by jkitman**
Fixes #2538

### CODE REVIEW

File: fedimint-server/src/config/mod.rs [hunk 1]
```diff
@@ -485,23 +485,28 @@ impl ServerConfig {
...
+                    None => Err(DkgError::ModuleNotFound(kind.clone())),
+                    Some(gen) => gen.distributed_gen(&dkg, module_params).await,
+                };
                 (module_instance_id, result)
             }
         });
         for (module_instance_id, config) in join_all(modules_runner).await {
-            module_cfgs.insert(module_instance_id, config?);
+            let config = config?;
+            registered_modules.remove(config.consensus_json.kind());
```
Comment (okjodom) [inline fedimint-server/src/config/mod.rs:505]: Took me a minute to understand why we remove each kind from known registered modules

**Review by okjodom — APPROVED** [review]
Neat

**Review by okjodom — APPROVED** [review]
