### PR TITLE
Fix crash on invalid member string

### LINKED ISSUE #925: ln-gateway panic on invalid connection msg
```
n_gateway: info;
2022-11-17T19:58:10.040Z INFO    plugin-ln_gateway: register;
thread 'main' panicked at 'Invalid federation connect info: Error("invalid type: floating point `127`, expected struct WsFederationConnect", line: 1, column: 5)', /home/dpc/lab/fedimint.git/main/gateway/ln-gateway/src/lib.rs:122:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'Failed to send over channel: RecvError(())', gateway/ln-gateway/src/rpc.rs:38:27
```

I accidentally connected  to ln-gateway port with a wrong command or something and caused a panic.

### PR DESCRIPTION
**Pull request by Maaxxs**
should fix #925

### CODE REVIEW

File: gateway/ln-gateway/src/lib.rs [hunk 1]
```diff
@@ -128,8 +128,13 @@ impl LnGateway {
 
     // Webserver handler for requests to register a federation
     async fn handle_register_federation(&self, payload: RegisterFedPayload) -> Result<()> {
-        let connect: WsFederationConnect =
-            serde_json::from_str(&payload.connect).expect("Invalid federation connect info");
+        let connect: WsFederationConnect = match serde_json::from_str(&payload.connect) {
+            Ok(value) => value,
+            Err(error) => {
+                error!("Invalid member string: {}", error);
+                return Ok(());
```
Comment (elsirion) [inline gateway/ln-gateway/src/lib.rs:135]: We should probably return the error to the caller since they might not be watching the gateway's log output. 

```rust
.map_err(|_| LnGatewayError::SomeApplicaleVariant))?
```

**Review by elsirion — CHANGES_REQUESTED** [review]

File: gateway/ln-gateway/src/lib.rs (hunk 1 above)
Comment (Maaxxs) [reply gateway/ln-gateway/src/lib.rs]: ah yes, that's more useful :+1:

**Comment by Maaxxs** [comment]
The current change would produce this error on the cmdline:
```
$ gateway-cli register-fed asdf
WARNING: Passing in a password from the command line may be less secure!

Error: Other(Other: Invalid federation member string

Caused by:
    Invalid federation member string)
```

and this in the logs:
```
2022-12-01T11:47:54.410Z INFO    plugin-ln_gateway: register;
2022-12-01T11:47:54.468Z **BROKEN** plugin-ln_gateway: error=Other: Other: Invalid federation member string\n\nCaused by:\n    Invalid federation member string
```

I'm not sure if I understood the `LnGatewayError::Other` correctly. Is it supposed to show the error message twice now?

**Review by elsirion — APPROVED** [review]
