### PR TITLE
fix(mint-client): reissuing eternal notes doesn't block

### LINKED ISSUE #4355: reissue_external_notes doesn't work offline
reissue_external_notes calls await_primary_module outputs, which makes it require network.

https://github.com/fedimint/fedimint/blob/3309fa26f2cc1388cb95e7e9166ff8d45b8253eb/modules/fedimint-mint-client/src/lib.rs#L1087-L1089

Ideally, this network request should be part of the state machine and reissue_external_notes should return while we are offline.

discussion on PR: https://github.com/fedimint/fedimint/pull/3227#discussion_r1492645077

### PR DESCRIPTION
**Pull request by elsirion**
Fixes #4355

### CODE REVIEW

File: modules/fedimint-mint-client/src/lib.rs [hunk 1]
```diff
@@ -341,7 +341,11 @@ pub struct MintOperationMeta {
 #[serde(rename_all = "snake_case")]
 pub enum MintOperationMetaVariant {
     Reissuance {
-        out_point: OutPoint,
+        // Deleted in 0.3.0:
+        // # out_point: OutPoint,
```
Comment (elsirion) [inline modules/fedimint-mint-client/src/lib.rs:345]: second thought: want to keep it around to still at least validate tx acceptance of old receives

File: modules/fedimint-mint-client/src/lib.rs [hunk 2]
```diff
@@ -341,7 +341,11 @@ pub struct MintOperationMeta {
...
+        // Introduced in 0.3.0:
+        #[serde(default)]
+        out_points: Vec<OutPoint>,
```
Comment (elsirion) [inline modules/fedimint-mint-client/src/lib.rs:348]: This encoding is highly redundant (always the same txid), do we care?

Comment (dpc) [reply modules/fedimint-mint-client/src/lib.rs:349]: If it's guaranteed to always be the same txid then oftentimes such redundancies are PITA down the line, even if not a storage problem. I guess `txid` + `Vec<uX>` is simple enough to do that why not?

Comment (elsirion) [reply modules/fedimint-mint-client/src/lib.rs]: Done, good point!

File: modules/fedimint-mint-client/src/lib.rs [hunk 3]
```diff
@@ -1098,8 +1115,26 @@ impl MintClientModule {
...
+                txid,
+                out_point_indices,
+            } => {
+                // Either txid or legacy_out_point will be present, so we should always
+                // have a source for the txid
+                let txid = txid
+                    .or(legacy_out_point.map(|out_point| out_point.txid))
+                    .context("Empty reissuance not permitted, this should never happen")?;
+
+                let out_points = out_point_indices
```
Comment (dpc) [inline modules/fedimint-mint-client/src/lib.rs:1130]: Thought: should we sort indices?

**Review by dpc — APPROVED** [review]

File: modules/fedimint-mint-client/src/lib.rs (hunk 3 above)
Comment (elsirion) [reply modules/fedimint-mint-client/src/lib.rs:1130]: They should always be ordered since they are generated from a `Range`:

https://github.com/fedimint/fedimint/blob/209c2f0aca73851faecd0040048a010a405512e1/fedimint-client/src/lib.rs#L1080-L1083

**Comment by fedimint-backports** [comment]
Backport failed for `releases/v0.2`, because it was unable to cherry-pick the commit(s).

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin releases/v0.2
git worktree add -d .worktree/backport-4384-to-releases/v0.2 origin/releases/v0.2
cd .worktree/backport-4384-to-releases/v0.2
git switch --create backport-4384-to-releases/v0.2
git cherry-pick -x 90a97cbb436ffa454b724c2081d2e02663c0942e
```
