### PR TITLE
fix: remove usage of assume_checked()

### LINKED ISSUE #5203: Remove usage of `assume_checked()`
Follow-up to #2356

Bitcoin v30 introduced the concept of checked and unchecked addresses. While migrating over from v0.29 to v0.30, I called `assume_checked()` wherever necessary to make the compiler happy. Now that the migration is complete, we should remove these calls and instead use [`require_network()`](https://docs.rs/bitcoin/0.30.2/bitcoin/address/struct.Address.html#method.require_network).

Edit: See [this comment](https://github.com/rust-bitcoin/rust-bitcoin/blob/master/bitcoin/CHANGELOG.md#changes-to-and-involving-the-network-type) in the changelog for `bitcoin` v0.32.0 which indicates that the work here might not be that important.

### PR DESCRIPTION
**Pull request by tvolk131**
Fixes #5203

Doesn't remove all usage of `assume_checked()`, since some uses are acceptable, such as in tests

### CODE REVIEW

File: fedimint-core/src/encoding/btc.rs [hunk 1]
```diff
@@ -203,10 +203,13 @@ impl Decodable for bitcoin::Amount {
 impl Encodable for bitcoin::Address<NetworkUnchecked> {
     fn consensus_encode<W: std::io::Write>(&self, writer: &mut W) -> Result<usize, Error> {
         let mut len = 0;
-        len += NetworkLegacyEncodingWrapper(get_network_for_address(self.as_unchecked()))
-            .consensus_encode(writer)?;
+        len +=
+            NetworkLegacyEncodingWrapper(get_network_for_address(self)).consensus_encode(writer)?;
         len += self
             .clone()
+            // We need an `Address<NetworkChecked>` in order to get the script pubkey.
```
Comment (dpc) [inline fedimint-core/src/encoding/btc.rs:210]: `assume_checked` is only a risk if the address is untrusted (provided from the outsdie). If we're encoding something, it is "internal" data, and should have been validated already, so it's OK.

File: gateway/ln-gateway/src/lib.rs [hunk 2]
```diff
@@ -889,6 +891,15 @@ impl Gateway {
             address,
             federation_id,
         } = payload;
+
+        let address_network = get_network_for_address(&address);
+        let gateway_network = self.gateway_config.read().await.network.0;
+        let Ok(address) = address.require_network(gateway_network) else {
+            return Err(AdminGatewayError::WithdrawError {
+                    failure_reason: format!("Gateway is running on network {gateway_network}, but provided withdraw address is for network {address_network}")
+                });
```
Comment (dpc) [inline gateway/ln-gateway/src/lib.rs:900]: Nit: indent seems slightly off.

File: gateway/ln-gateway/src/lib.rs [hunk 3]
```diff
@@ -900,7 +911,7 @@ impl Gateway {
                 let balance =
                     bitcoin::Amount::from_sat(client.value().get_balance().await.msats / 1000);
                 let fees = wallet_module
-                    .get_withdraw_fees(address.clone(), balance)
+                    .get_withdraw_fees(address.as_unchecked().clone(), balance)
```
Comment (dpc) [inline gateway/ln-gateway/src/lib.rs:914]: Shouldn't we modify methods to take "checked" address instead? We should generally use `Checked` all over the code, except in deserialization / taking input from the user, where we sould make sure to validate them.

File: gateway/ln-gateway/src/lib.rs (hunk 2 above)
Comment (tvolk131) [reply gateway/ln-gateway/src/lib.rs]: Fixed

File: gateway/ln-gateway/src/lib.rs (hunk 3 above)
Comment (tvolk131) [reply gateway/ln-gateway/src/lib.rs]: Good point! Fixed.

File: fedimint-core/src/encoding/btc.rs (hunk 1 above)
Comment (tvolk131) [reply fedimint-core/src/encoding/btc.rs:210]: Currently we implement `Encodable` and `Decodable` for unchecked addresses but not checked addresses, requiring us to re-check the network for addresses that, as you mention, are trusted to be already checked. What do you think about changing the implementations to be for checked addresses instead? That way, we could remove the few places where we're calling `into_unchecked()` or `as_unchecked()` when encoding data and likewise remove the need to re-check addresses when decoding them.

Comment (tvolk131) [reply fedimint-core/src/encoding/btc.rs:210]: I made #6550 to showcase this. However, since it requires the removal of `serde::Deserialize` for structs containing a checked address, it probably isn't worth it.

Comment (dpc) [reply fedimint-core/src/encoding/btc.rs:210]: @tvolk131 Maybe we should parametrize with aliases?


```
struct SomeAggregateType<V = NetworkUnchecked> {
  ...
  addresss: Address<V>,
  ...
}

type CheckedSomeAggregateType = SomeAggregateType<NetworkChecked>;

impl SomeAggregateType<NetworkUnchecked> {
  fn validate_network(...) -> ... {

  }
}
```

Database definitions can just use `CheckedSomeAggregateType` everywhere, while networking code the (unchecked) `SomeAggregateType`?

@tvolk131

Comment (elsirion) [reply fedimint-core/src/encoding/btc.rs:210]: Feels like too much overhead to me tbh.

File: modules/fedimint-wallet-server/src/lib.rs [hunk 4]
```diff
@@ -1408,15 +1410,30 @@ impl Wallet {
...
+                    .clone()
+                    .require_network(self.cfg.consensus.network.0)
+                    .map_err(|_| {
+                        WalletOutputError::WrongNetwork(
+                            self.cfg.consensus.network.clone(),
+                            NetworkLegacyEncodingWrapper(get_network_for_address(
+                                &peg_out.recipient,
+                            )),
+                        )
+                    })?;
```
Comment (elsirion) [inline modules/fedimint-wallet-server/src/lib.rs:1425]: This is a consensus change unless proven otherwise. We can forbid submitting withdrawal addresses with incorrect network, but forbidding them in consensus may break guardian recovery from a peer's history if someone already submitted such a transaction.

We could phase it in through a consensus version vote, something we already implemented in the wallet module anyway. cc @bradleystachurski @joschisan

**Review by elsirion — CHANGES_REQUESTED** [review]

File: modules/fedimint-wallet-server/src/lib.rs (hunk 4 above)
Comment (tvolk131) [reply modules/fedimint-wallet-server/src/lib.rs:1425]: Ahh good catch! I wonder if this is worth a consensus change... I think it would make sense to drop a comment describing why we're calling `assume_checked()` and otherwise leave this code alone. We're eventually going to replace it with wallet v2 anyway.

Comment (elsirion) [reply modules/fedimint-wallet-server/src/lib.rs:1425]: It's also more of a user foot-gun, for everything that matters we use script anyway, so nothing should blow up even if someone submits a wrong network address on purpose (the client won't do that on its own).

Comment (tvolk131) [reply modules/fedimint-wallet-server/src/lib.rs]: Fixed! Also we already do reject transactions with the wrong network in `validate_tx()` which we call in `process_output()`:

https://github.com/fedimint/fedimint/blob/3b27f563b86ca3cd68e4f5b2399f9d10a79122bb/modules/fedimint-wallet-server/src/lib.rs#L713-L717

**Review by elsirion — APPROVED** [review]
