### PR TITLE
fix(mint-client): reject zero-value out-of-band spends

### LINKED ISSUE #3182: Make sure we can handle serialized `TieredMulti<SpendableNote>` with no notes inside it
Somewhere we might assume that this isn't empty -- for instance, in the creation of operation ids.

### PR DESCRIPTION
**Pull request by elsirion**
These could lead to weird error messages since all zero-value OOB spends have the same identity. All but the first would fail.

Fixes #3182

### CODE REVIEW

File: modules/fedimint-mint-tests/tests/tests.rs [hunk 1]
```diff
@@ -40,3 +40,39 @@ async fn sends_ecash_out_of_band() -> anyhow::Result<()> {
...
+    let res = client1
+        .reissue_external_notes(
+            OOBNotes {
+                federation_id: client1.federation_id(),
+                notes: Default::default(),
+            },
+            (),
+        )
+        .await;
+    assert!(res.is_err(), "Zero-amount receives should be forbidden");
```
Comment (elsirion) [inline modules/fedimint-mint-tests/tests/tests.rs:76]: I should check the error message.

File: modules/fedimint-mint-client/src/lib.rs [hunk 2]
```diff
@@ -248,6 +248,11 @@ impl MintClientExt for Client {
             federation_id,
             notes,
         } = oob_notes;
+        ensure!(
```
Comment (dpc) [inline modules/fedimint-mint-client/src/lib.rs:251]: Should we reject these on deserialization level?

Comment (elsirion) [reply modules/fedimint-mint-client/src/lib.rs:251]: Maybe? It just seemed more natural to do it here because at least generating them has to be prevented in the client impl. I could add a second line of defense on the decoding level I guess.

Comment (elsirion) [reply modules/fedimint-mint-client/src/lib.rs:255]: Addressed in [48a8125](https://github.com/fedimint/fedimint/pull/3281/commits/48a8125d2b26600cbe0903f5d9e1e393c936026b)

**Review by dpc — APPROVED** [review]

File: modules/fedimint-mint-client/src/lib.rs [hunk 3]
```diff
@@ -93,10 +93,14 @@ impl FromStr for OOBNotes {
     /// Decode a set of out-of-band e-cash notes from a base64 string.
     fn from_str(s: &str) -> Result<Self, Self::Err> {
         let bytes = base64::decode(s)?;
-        Ok(Decodable::consensus_decode(
+        let oob_notes: OOBNotes = Decodable::consensus_decode(
```
Comment (dpc) [inline modules/fedimint-mint-client/src/lib.rs:96]: Oh, I thought we would do it by making a custom implementation of `Decodable` & `Encodable`. :)

**Review by justinmoon — APPROVED** [review]

**Comment by dpc** [comment]
> Oh, I thought we would do it by making a custom implementation of Decodable & Encodable. :)

Boo, landed. I think it would be much more solid if done there. @elsirion

**Comment by elsirion** [comment]
Right, we could make it an invariant, but then we need a constructor that checks it too. That would make sense *instead* of the current approach, but I understood your comment as adding an earlier failure point in addition. Can always change it again.
