### PR TITLE
fix: implement variantless enum encode/decode derive

### LINKED ISSUE #1398: Derive encodable doesn't work with `enum NotPossible {}`.
Can be useful for modules that don't use `Input/Ouput/etc.`

### PR DESCRIPTION
**Pull request by elsirion**
fixes #1398

### CODE REVIEW

File: fedimint-derive/src/lib.rs [hunk 1]
```diff
@@ -121,7 +121,16 @@ pub fn derive_encodable(input: TokenStream) -> TokenStream {
             }
         }
         syn::Data::Enum(DataEnum { variants, .. }) => {
-            let match_arms = variants.iter().enumerate().map(|(variant_idx, variant)| {
+            if variants.is_empty() {
+                quote! {
+                    impl Encodable for #ident {
+                        fn consensus_encode<W: std::io::Write>(&self, _writer: &mut W) -> std::result::Result<usize, std::io::Error> {
+                            unreachable!("Enum without variants can't exist")
```
Comment (Maan2003) [inline fedimint-derive/src/lib.rs:128]:
```suggestion
                            match self { }
```

Comment (dpc) [reply fedimint-derive/src/lib.rs:128]: LGTM, but this one worth fixing before landing.

Comment (elsirion) [reply fedimint-derive/src/lib.rs]: Done. Most interestingly I had to dereference the enum or [I would get this error](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021):

Screenshot 2023-01-19 at 14-05-56 Rust Playground

**Review by dpc — APPROVED** [review]
