### PR TITLE
fix: fedimint-cli invite-code

### LINKED ISSUE #3178: `fedimint-cli dev invite-code` broken in mprocs
and I don't see how the current impl could ever work since the client is restarted for every command, resetting the internal state that's not persisted to DB. Maybe we should just save the invite code to the DB so this functionality can be implemented properly.

### PR DESCRIPTION
**Pull request by okjodom**
Removes `invite-code` command from `fedimint-cli dev` and re-adds it as a non-dev command. The invite code is sourced from client database where it was stored the first time a client is created

fixes #3178

### CODE REVIEW

File: fedimint-client/src/lib.rs [hunk 1]
```diff
@@ -1605,6 +1607,18 @@ pub async fn get_config_from_db(db: &Database) -> Option<ClientConfig> {
     config
 }
 
+pub async fn get_invite_code_from_db(db: &Database) -> Option<InviteCode> {
+    let mut dbtx = db.begin_transaction().await;
+    #[allow(clippy::let_and_return)]
+    let invite = dbtx
+        .find_by_prefix(&ClientInviteCodeKeyPrefix)
```
Comment (dpc) [inline fedimint-client/src/lib.rs:1614]: **thought:** We should just have `DatabaseTransaction:find_singleton(key) -> Option<T>` with a default impl to make this pattern more usable.

File: fedimint-client/src/lib.rs [hunk 2]
```diff
@@ -1605,6 +1607,18 @@ pub async fn get_config_from_db(db: &Database) -> Option<ClientConfig> {
     config
 }
 
+pub async fn get_invite_code_from_db(db: &Database) -> Option<InviteCode> {
+    let mut dbtx = db.begin_transaction().await;
+    #[allow(clippy::let_and_return)]
```
Comment (dpc) [inline fedimint-client/src/lib.rs:1612]: **suggestion:** I would just apply the suggested clippy fix. Makes sense to me.

**Review by dpc — APPROVED** [review]
I tried and it works. Some suggestions, but LGTM.

File: fedimint-client/src/lib.rs (hunk 1 above)
Comment (justinmoon) [reply fedimint-client/src/lib.rs:1614]: Thoughts @m1sterc001guy?

File: fedimint-client/src/lib.rs (hunk 2 above)
Comment (okjodom) [reply fedimint-client/src/lib.rs:1647]: we need to drop dbtx before other local vars which forces us to use let and return

Comment (dpc) [reply fedimint-client/src/lib.rs:1647]:
```
pub async fn get_config_from_db(db: &Database) -> Option<ClientConfig> {
    db.begin_transaction()
        .await
        .find_by_prefix(&ClientConfigKeyPrefix)
        .await
        .next()
        .await
        .map(|(_, config)| config)
}
```

Works.

**Comment by justinmoon** [comment]
@okjodom Does this close https://github.com/fedimint/fedimint/issues/2556?

**Comment by okjodom** [comment]
Yes, but also the issue is outdated. command is now `fedimint-cli invite-code`
