### PR TITLE
Fix potential attack against DKG

### LINKED ISSUE #760: Fix potential attack against DKG
According to [this blog](https://blog.sigmaprime.io/dkg-rogue-key.html), there is an attack against Gennaro et al. DKG

I don't know whether the attack method is substantiated by other research, but the solution of adding an additional step to commit to the cryptographic hash of the commit polynomial would not add any risks.

### PR DESCRIPTION
**Pull request by jkitman**
Requires peers to commit to a hash prior to revealing their commitments to avoid manipulation of the secret key.

Long-term will need to revisit DKG to deal with issues of liveness, but we can at least be assured if DKG runs that no one knows the secret key.

Fixes #760

### CODE REVIEW

File: fedimint-api/src/config.rs [hunk 1]
```diff
@@ -96,17 +104,33 @@ impl<G: DkgGroup> Dkg<G> {
...
     }
 
     /// Runs a single step of the DKG algorithm, processing a `msg` from `peer`
     pub fn step(&mut self, peer: PeerId, msg: DkgMessage<G>) -> DkgStep<G> {
         match msg {
+            DkgMessage::HashedCommit(hashed) => {
+                match self.hashed_commits.get(&peer) {
+                    Some(old) if *old != hashed => panic!("{} sent us two hashes!", peer),
+                    _ => self.hashed_commits.insert(peer, hashed),
+                };
```
Comment (elsirion) [inline fedimint-api/src/config.rs:122]: This could be `assert!(self.hashed_commits.insert(peer, hashed).is_none())` or a similar if clause for better panic messages.

**Review by elsirion — APPROVED** [review]
The fix has the shortcomings mentioned in #760, but it's an improvement imo. Feel free to address the nit or merge.

File: fedimint-api/src/config.rs (hunk 1 above)
Comment (jkitman) [reply fedimint-api/src/config.rs:122]: So actually I've noticed in practice that messages can be sent twice over the network, which cause that assertion to fail, this is why I must check for non-equality.

Comment (elsirion) [reply fedimint-api/src/config.rs:122]: Interesting! Shouldn't this be prevented? Maybe that's a bug in the network layer?

Comment (dpc) [reply fedimint-api/src/config.rs:122]: I'm out of context, but since I casually looking at it: It's not possible to have an atomic transaction over both persistence and network message, so generally "at least once delivery" is usually used, which means duplicated messages must be handled and idempotently.
