### PR TITLE
chore: fix clippy warnings (v0.4 backport)

### LINKED ISSUE #5617: Backport PR `#5606` chore: fix clippy warnings
PR: #5606
Title: chore: fix clippy warnings

The backport bot failed. Please open a PR to backport these changes.

### PR DESCRIPTION
**Pull request by dpc**
Backport #5606
Fix #5617

### CODE REVIEW

**Review by maan2003 — APPROVED** [review]

File: modules/fedimint-lnv2-tests/src/bin/tests.rs [hunk 1]
```diff
@@ -81,15 +81,15 @@ async fn test_self_payment(dev_fed: &DevJitFed) -> anyhow::Result<()> {
...
+    gw_address: &str,
 ) -> anyhow::Result<(Bolt11Invoice, OperationId)> {
     Ok(serde_json::from_value::<(Bolt11Invoice, OperationId)>(
         cmd!(
             client,
             "module",
             "lnv2",
             "receive",
-            gw_address.clone(),
+            gw_address.to_owned(),
```
Comment (tvolk131) [inline modules/fedimint-lnv2-tests/src/bin/tests.rs:92]: Nit: Do we even need `.to_owned()`? I think we can just put `gw_address`

**Review by tvolk131 — CHANGES_REQUESTED** [review]

File: modules/fedimint-lnv2-tests/src/bin/tests.rs (hunk 1 above)
Comment (dpc) [reply modules/fedimint-lnv2-tests/src/bin/tests.rs]: Right.
