### PR TITLE
fix(tests): retry client balance check to prevent flakiness

### LINKED ISSUE #6190: Flake in rbf_withdrawals_are_rejected
```
 fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:18 thread 'rbf_withdrawals_are_rejected' panicked at modules/fedimint-wallet-tests/tests/tests.rs:499:5:
 fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:18 assertion `left == right` failed: Balance is 7038000 msat, expected 7256000 msat
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:18   left: Amount { msats: 7038000 }
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:18  right: Amount { msats: 7256000 }
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:18 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

https://github.com/fedimint/fedimint/actions/runs/11423491767/job/31782749548

### PR DESCRIPTION
**Pull request by bradleystachurski**
Closes #6190

### CODE REVIEW

File: modules/fedimint-wallet-tests/tests/tests.rs [hunk 1]
```diff
@@ -497,11 +497,30 @@ async fn rbf_withdrawals_are_rejected() -> anyhow::Result<()> {
         sats(PEG_OUT_AMOUNT_SATS)
     );
 
-    let current_balance = client.get_balance().await;
-    assert_eq!(
-        current_balance, balance_after_normal_peg_out,
-        "Balance is {current_balance}, expected {balance_after_normal_peg_out}"
-    );
+    // to prevent flakiness, we need to retry this check
```
Comment (dpc) [inline modules/fedimint-wallet-tests/tests/tests.rs:500]: Yeah, the race condition here is that just because withdrawal failed, doesn't mean the refund was already processed.

**Review by dpc — APPROVED** [review]
