### PR TITLE
chore(api-client): fix logging targets

### LINKED ISSUE #7975: fedimit-api-client should use `LOG_CLIENT_NET`

### PR DESCRIPTION
**Pull request by dpc**
Fix #7975

### CODE REVIEW

File: fedimint-api-client/src/api/mod.rs [hunk 1]
```diff
@@ -142,7 +142,7 @@ pub trait FederationApiExt: IRawFederationApi {
 
     /// Make an aggregate request to federation, using `strategy` to logically
     /// merge the responses.
-    #[instrument(target = LOG_NET_API, skip_all, fields(method=method))]
+    #[instrument(target = LOG_CLIENT_NET, skip_all, fields(method=method))]
```
Comment (bradleystachurski) [inline fedimint-api-client/src/api/mod.rs]: `request_with_strategy_retry` already uses `LOG_CLIENT_NET_API`. Is there a reason to specifically use `LOG_CLIENT_NET` here instead of `LOG_CLIENT_NET_API`? Logging to different targets might be confusing.

https://github.com/fedimint/fedimint/blob/62b3953048e8e94d13f8001cf91a7945a192d26c/fedimint-api-client/src/api/mod.rs#L222-L223

**Review by bradleystachurski — COMMENTED** [review]
Should we use `LOG_CLIENT_NET_API` for all targets in `fedimint-api-client/src/api/mod.rs`?

File: fedimint-api-client/src/api/mod.rs (hunk 1 above)
Comment (dpc) [reply fedimint-api-client/src/api/mod.rs]: You're absolutely right! Let me fix it.

Done.

**Review by bradleystachurski — APPROVED** [review]
