### PR TITLE
fix: use default port for p2p connections if none was specified

### LINKED ISSUE #6287: Fedimint allows missing port on FM_P2P_URL
Trying to setup a new federation we got stuck on this:

```
fedimintd  | 2024-11-05T18:13:54.009711Z DEBUG spawn{task="io-thread-peer-3"}:run_io_thread: fm::net::peer: Peer disconnected our_id=PeerId(0) peer=PeerId(3) err=Missing port in fedimint://xxx.yyyy.zzzz disconnect_count=89
```

The guardian didn't specify a port on FM_P2P_URL and fedimint/guardian ui didn't error about this.

### PR DESCRIPTION
**Pull request by elsirion**
Fixes  #6287

### CODE REVIEW

File: fedimint-server/src/net/connect.rs [hunk 1]
```diff
@@ -232,12 +237,13 @@ pub fn dns_sanitize(name: &str) -> String {
 }
 
 /// Parses the host and port from a url
-pub fn parse_host_port(url: &SafeUrl) -> anyhow::Result<String> {
+pub fn parse_host_port(url: &SafeUrl, fallback_port: Option<u16>) -> anyhow::Result<String> {
     let host = url
         .host_str()
         .ok_or_else(|| format_err!("Missing host in {url}"))?;
     let port = url
         .port()
```
Comment (dpc) [inline fedimint-server/src/net/connect.rs:245]: There's already `SafeUrl::port_or_known_default`

Comment (elsirion) [reply fedimint-server/src/net/connect.rs:245]: Totally forgot about that, thx!

**Review by dpc — APPROVED** [review]
So minimal. :)
