### PR TITLE
fix: Print lightning gateway version at startup

### LINKED ISSUE #1607: `ln_gateway` should print out its code version
@asifshiraz Could you have `ln_gateway` also print out it code version?

_Originally posted by @justinmoon in https://github.com/fedimint/fedimint/issues/1581#issuecomment-1421136411_

### PR DESCRIPTION
**Pull request by asifshiraz**
fixes #1607

### CODE REVIEW

File: gateway/ln-gateway/src/lib.rs [hunk 1]
```diff
@@ -118,6 +118,9 @@ impl LnGateway {
             .load_federation_actors(decoders, module_gens, route_hints)
             .await;
 
+        let version = env!("GIT_HASH").to_string();
+        info!("Starting lightning gateway (version: {version}");
```
Comment (mxz42) [inline gateway/ln-gateway/src/lib.rs:122]: This currently prints 

```
2023-02-08T16:44:31.786Z INFO    plugin-ln_gateway: Starting lightning gateway (version: 04a59457a253243428dab6dc4aa844d1ac4577a9
```
There's a missing closing `)` or better remove the opening `(` I guess :)

Also, since we only print the version hash, we don't need to allocate via `.to_string()`. We can just take the `&str` from the `env` macro.

Comment (dpc) [inline gateway/ln-gateway/src/lib.rs:122]: BTW. Just looking at it now, we should use structural logging like this: ` info!(version, "Starting lightning gateway");` (or `%version`).

**Comment by mxz42** [comment]
just another thought: maybe move the logging statement to the start of the `new` method, so that it's the first logging statement that appears for ln_gateway before `LnRpc::route_hints;` and `LnRpc::pubkey;` and so on. So that even if one of these calls fail, the version is already printed.

File: gateway/ln-gateway/src/lib.rs (hunk 1 above)
Comment (asifshiraz) [reply gateway/ln-gateway/src/lib.rs]: Done

**Review by dpc — DISMISSED** [review]

**Review by mxz42 — APPROVED** [review]

**Review by dpc — APPROVED** [review]

**Review by mxz42 — APPROVED** [review]

**Comment by mxz42** [comment]
thanks! @asifshiraz
