### PR TITLE
fix: reissue ecash after recovery to avoid invalid wallet states

### LINKED ISSUE #7890: Rissue all ecash after recovery
If there's any in-flight OOB ecash you could otherwise get already-spent ecash if the party who received the OOB notes claims them after you recovered.

### PR DESCRIPTION
**Pull request by elsirion**
Fixes #7890

### CODE REVIEW

File: modules/fedimint-mint-client/src/backup/recovery.rs [hunk 1]
```diff
@@ -182,25 +193,70 @@ impl RecoveryFromHistory for MintRecovery {
...
+        let operation_id = OperationId::new_random();
+        let mut out_point_ranges = Vec::new();
+        let reissue_amount = finalized.spendable_notes.total_amount();
+
+        // We reissue notes in chunks to avoid hitting consensus size limits and in the
+        // future minimize transaction fees.
+        for notes in finalized
+            .spendable_notes
+            .into_iter_items()
+            .chunks(MAX_REISSUE_NOTES_PER_TX)
```
Comment (dpc) [inline modules/fedimint-mint-client/src/backup/recovery.rs:208]: I would collect these in a Vec, shuffle, then split into `N * rand() % N` chunks as an easiest level of obfuscation that has a chance of splitting the amount and does not near-100% give a way that a recovery is being made.
