### PR TITLE
fix(rocksdb): map RocksDB transient errors to retriable context

### LINKED ISSUE #8077: Unrecoverable error occurred while committing to the database.: Resource busy:
```

test-ci-all> fm0
test-ci-all> fm0 thread 'tokio-runtime-worker2025-12-12T21:36:59.522134Z  WARN fm::net::api: Failed to handle iroh connection err=closed by peer: 0
test-ci-all> fm0 ' panicked at /build/source/fedimint-core/src/db/mod.rs:1890:14:
test-ci-all> fm0 Unrecoverable error occurred while committing to the database.: Resource busy:
test-ci-all> fm0
test-ci-all> fm0 Stack backtrace:
test-ci-all> fm0    0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
test-ci-all> fm0              at /nix/store/66q5z6a5zi93xl3kx4x4irfwz40a4r57-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/anyhow-1.0.98/src/backtrace.rs:27:14
test-ci-all> fm0    1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
test-ci-all> fm0              at /nix/store/8ayri7zwfrk1131s499dd1h66zny9gsi-rust-mixed/lib/rustlib/src/rust/library/core/src/result.rs:2079:27
test-ci-all> fm0    2: <fedimint_rocksdb::RocksDbTransaction as fedimint_core::db::IRawDatabaseTransaction>::commit_tx::{{closure}}::{{closure}}
test-ci-all> fm0              at ./fedimint-rocksdb/src/lib.rs:363:13
test-ci-all> fm0    3: tokio::runtime::context::runtime_mt::exit_runtime
test-ci-all> fm0              at /nix/store/66q5z6a5zi93xl3kx4x4irfwz40a4r57-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.48.0/src/runtime/context/runtime_mt.rs:35:5
test-ci-all> fm0    4: tokio::runtime::scheduler::multi_thread::worker::block_in_place
test-ci-all> fm0              at /nix/store/66q5z6a5zi93xl3kx4x4irfwz40a4r57-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.48.0/src/runtime/scheduler/multi_thread/worker.rs:448:9
test-ci-all> fm0    5: tokio::runtime::scheduler::block_in_place::block_in_place
test-ci-all> fm0              at /nix/store/66q5z6a5zi93xl3kx4x4irfwz40a4r57-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.48.0/src/runtime/scheduler/block_in_place.rs:8:5
test-ci-all> fm0    6: tokio::task::blocking::block_in_place
test-ci-all> fm0              at /nix/store/66q5z6a5zi93xl3kx4x4irfwz40a4r57-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.48.0/src/task/blocking.rs:78:9
test-ci-all> fm0    7: fedimint_core::runtime::block_in_place
test-ci-all> fm0              at ./fedimint-core/src/runtime.rs:30:5
test-ci-all> fm0    8: <fedimint_rocksdb::RocksDbTransaction as fedimint_core::db::IRawDatabaseTransaction>::commit_tx::{{closure}}
test-ci-all> fm0              at ./fedimint-rocksdb/src/lib.rs:362:9
test-ci-all> fm0    9: {async_block#0}<fedimint_rocksdb::RocksDbTransaction>
test-ci-all> fm0              at ./fedimint-core/src/db/mod.rs:1469:14
test-ci-all> fm0   10: {async_block#0}<dyn fedimint_core::db::IDatabaseTransaction>
test-ci-all> fm0              at ./fedimint-core/src/db/mod.rs:1301:30
test-ci-all> fm0   11: {async_fn#0}
test-ci-all> fm0              at ./fedimint-core/src/db/mod.rs:1874:49
test-ci-all> fm0   12: {async_fn#0}
test-ci-all> fm0              at ./fedimint-core/src/db/mod.rs:1889:14
test-ci-all> fm0   13: {async_fn#0}
test-ci-all> fm0              at ./fedimint-server/src/consensus/api.rs:500:26
test-ci-all> fm0   14: {async_block#0}
test-ci-all> fm0              at ./fedimint-server/src/consensus/api.rs:923:106
```

https://github.com/fedimint/fedimint/actions/runs/20180541458/job/57939617495

### PR DESCRIPTION
**Pull request by devvaansh**
Fixes #8077, Handle OptimisticTransactionDB busy errors by: Distinguishing retriable errors (Busy, TryAgain, MergeInProgress, TimedOut)
 Returning errors with (retriable) context instead of panicking
 Converting submit_api_announcement to use autocommit with retry logic

### CODE REVIEW

File: fedimint-rocksdb/src/lib.rs [hunk 1]
```diff
@@ -402,17 +402,25 @@ impl IDatabaseTransactionOps for RocksDbTransaction<'_> {
...
+                    // RocksDB's OptimisticTransactionDB can return Busy/TryAgain errors
+                    // when concurrent transactions conflict on the same keys.
+                    // These are retriable - the caller should retry the entire transaction.
+                    // See: https://github.com/fedimint/fedimint/issues/8077
+                    match err.kind() {
+                        rocksdb::ErrorKind::Busy
+                        | rocksdb::ErrorKind::TryAgain
+                        | rocksdb::ErrorKind::MergeInProgress
+                        | rocksdb::ErrorKind::TimedOut => Err(anyhow::anyhow!(err)
+                            .context("RocksDB optimistic transaction conflict (retriable)")),
```
Comment (dpc) [inline fedimint-rocksdb/src/lib.rs]: Why not `DatabaseError::WriteConflict`?

Comment (devvaansh) [reply fedimint-rocksdb/src/lib.rs]: @dpc  You are right, I have updated the code to use `DatabaseError::WriteConflict` instead of anyhow errors with string context. this makes it consistent with how other database implementations (mem_impl, cursed-redb) handle write conflicts.

**Comment by dpc** [comment]
LGTM, I guess. @elsirion I remember briefly discussing with you some concerns w.r.t autoretries.

**Review by m1sterc001guy — APPROVED** [review]
Also LGTM, but we can wait for @elsirion on the auto-commit of transactions. I don't see any issue with it though

**Comment by devvaansh** [comment]
Lints are now fixed and all checks are green @dpc

**Review by dpc — APPROVED** [review]

File: fedimint-rocksdb/src/lib.rs [hunk 2]
```diff
@@ -402,17 +402,22 @@ impl IDatabaseTransactionOps for RocksDbTransaction<'_> {
...
+                Err(err) => {
+                    // RocksDB's OptimisticTransactionDB can return Busy/TryAgain errors
+                    // when concurrent transactions conflict on the same keys.
+                    // These are retriable - return WriteConflict so autocommit retries.
+                    // See: https://github.com/fedimint/fedimint/issues/8077
+                    match err.kind() {
+                        rocksdb::ErrorKind::Busy
+                        | rocksdb::ErrorKind::TryAgain
+                        | rocksdb::ErrorKind::MergeInProgress
+                        | rocksdb::ErrorKind::TimedOut => Err(DatabaseError::WriteConflict),
```
Comment (elsirion) [inline fedimint-rocksdb/src/lib.rs:416]: @elsirion is this all the variants we want to retry on?

Comment (devvaansh) [reply fedimint-rocksdb/src/lib.rs:416]: Hi @elsirion, I based this list on the most common transient/locking errors reported in RocksDB optimistic transactions. If you think we should include others (like specific IO sub-codes), I am happy to open a follow up PR to expand the mapping
