### PR TITLE
fix(client): ignore user data in the new-db check

### LINKED ISSUE #5706: incorrect assumption about empty database
https://github.com/fedimint/fedimint/blob/50e895058b2e01b95df39a0439b19dd06dd6a0d7/fedimint-core/src/db/mod.rs#L1934-L1937

this is incorrect because external application (client integrators) may store data in the database ExternalReservedStart)

### PR DESCRIPTION
**Pull request by dpc**
Fix #5706

### CODE REVIEW

**Comment by dpc** [comment]
@maan2003 @m1sterc001guy

**Review by maan2003 — COMMENTED** [review]
we use all prefixes from `0xb1` to `0xbf` unfortunately in fedi.

**Comment by dpc** [comment]
> we use all prefixes from `0xb1` to `0xbf` unfortunately in fedi.

I don not understand. In this PR I ignore everything from 0xb0 and above.

File: fedimint-core/src/db/mod.rs [hunk 1]
```diff
@@ -1930,11 +1930,26 @@ pub async fn apply_migrations(
...
     // Newly created databases will not have any data since they have just been
     // instantiated.
     let mut dbtx = db.begin_transaction_nc().await;
-    let is_new_db = dbtx.raw_find_by_prefix(&[]).await?.next().await.is_none();
+    let is_new_db = dbtx
+        .raw_find_by_prefix(&[])
+        .await?
+        .filter(|(key, _v)| {
+            std::future::ready(
+                external_prefixes_above.map_or(true, |external_prefixes_above| {
```
Comment (maan2003) [inline fedimint-core/src/db/mod.rs:1945]: nit: move this to if let outside the filter, we don't have to pay the checking cost on server side

i would be really suprised if compiler is able optimize through streams wrapper

**Review by maan2003 — APPROVED** [review]
oh smart, I didn't read code before

File: fedimint-core/src/db/mod.rs (hunk 1 above)
Comment (dpc) [reply fedimint-core/src/db/mod.rs:1945]: True, but comparing to the IO this really doesn't matter. My guestimate is orders of magnitude (1ns vs 1us) differences. And this code runs ones on start anyway.

File: fedimint-client/src/db.rs [hunk 2]
```diff
@@ -432,7 +432,15 @@ pub async fn apply_migrations_core_client(
...
     migrations: BTreeMap<DatabaseVersion, CoreMigrationFn>,
 ) -> Result<(), anyhow::Error> {
-    apply_migrations(db, kind, target_version, migrations, None).await
+    apply_migrations(
+        db,
+        kind,
+        target_version,
+        migrations,
+        None,
+        Some(DbKeyPrefix::UserData as u8),
```
Comment (bradleystachurski) [inline fedimint-client/src/db.rs:441]: This will also filter out `InternalReservedStart` and `ModuleGlobalPrefix`. Will that cause any issues for detecting if it's a new db?

**Comment by fedimint-backports** [comment]
Successfully created backport PR for `releases/v0.4`:
- #5719
