### PR TITLE
fix: ln client doesn't retry on preimage pending decryption

### LINKED ISSUE #1795: `await_preimage_decryption` doesn't retry on `Pending`
`await_preimage_decryption` calls `await_output_outcome` which will return:

```
    LN(                                                                                                                                                         
        Contract {                                                                                                                                                          id: be3d072c81b3efc01c4ad8fa51ca274c3f61f21db09ce4f1b0945dd9041afb82,                                                                               
            outcome: Incoming(                                                                                                                                                  Pending,                                                                                                                                        
            ),                                                                                                                                                  
        },                                                                                                                                                          ),   
```

which technically is not an output outcome error. After receiving it the `buy_preimage_from_federation_await_decryption` immediately fails and runs `refund_incoming_contract` .

### PR DESCRIPTION
**Pull request by dpc**
This is a source of test flakiness.

Fix #1795

### CODE REVIEW

File: client/client-lib/src/lib.rs [hunk 1]
```diff
@@ -1415,16 +1416,39 @@ impl Client<GatewayClientConfig> {
...
-        Ok(self
-            .context
-            .api
-            .await_output_outcome::<OutputOutcome>(
-                outpoint,
-                Duration::from_secs(10),
-                &self.context.decoders,
+        let deadline = Instant::now().add(Duration::from_secs(30));
+
+        let poll = || async {
```
Comment (okjodom) [inline client/client-lib/src/lib.rs:1421]: Poll looks like a variant of retry. Is our existing [retry utility ](https://github.com/fedimint/fedimint/blob/master/gateway/ln-gateway/src/utils.rs#L16) applicable for this?

Comment (dpc) [reply client/client-lib/src/lib.rs:1421]: It has to be deadline based, not attempt-s based, so I don't think so.

Comment (dpc) [reply client/client-lib/src/lib.rs:1421]: I don't know if it's worth adding one for it either. Maybe if we converted more code to use deadlines it would make sense.

**Comment by justinmoon** [comment]
Is there anywhere else in the codebase where we should be polling with a deadline?

**Review by justinmoon — APPROVED** [review]

**Comment by dpc** [comment]
> Is there anywhere else in the codebase where we should be polling with a deadline?
> 
> Looked a little and couldn't find anything ...

We should always use deadlines. Deadlines are the best. But not in this PR. :D

**Review by okjodom — APPROVED** [review]
