### PR TITLE
switch ecash denominations to powers of 2

### LINKED ISSUE #332: Client coin selection should fail if it can't make correct change
For example, in the current `tmuxinator` setup we have a minimum denomination size of 1 sat. If client tries to pay a 1 msat lightning invoice, it will submit an unbalanced transaction to the federation:

```
$ ln2 invoice 1 test test
$  mint_client ln-pay lnbcrt10p...
...
thread 'main' panicked at 'Not enough coins: MintClientError(ApiError(RpcError(RestartNeeded("Networking or low-level protocol error: WebSocket connection error: connection closed"))))', client/cli/src/main.rs:188:18
```

The federation logs will have the following error:

```
thread 'tokio-runtime-worker' panicked at 'Could not submit sign request to consensus: TransactionError(UnbalancedTransaction { inputs: Amount { milli_sat: 1000 }, outputs: Amount { milli_sat: 1 }, fee: Amount { milli_sat: 0 }})', minimint/src/net/api.rs:118:22
```

### LINKED ISSUE #674: tmuxinator should have millisat denominations
Tmuxinator stops at 1 sat as minimum denomination. In the interest of not confusing new users, we should probably have 1, 10, and 100 millisat denominations. Errors about "unbalanced transactions" will confuse new people.

### PR DESCRIPTION
**Pull request by jkitman**
Switching to denominations as powers of 2 to simplify code and reduce chance of errors.  More reasoning explained here https://github.com/fedimint/fedimint/issues/116#issuecomment-1332598851

Fixes #332, fixes #674

### CODE REVIEW

File: fedimint-server/src/config.rs [hunk 1]
```diff
@@ -410,6 +401,19 @@ pub struct PeerServerParams {
...
 impl ServerConfigParams {
+    /// Generates denominations as powers of 2 until a `max`
+    pub fn gen_denominations(max: Amount) -> Vec<Amount> {
+        let mut amounts = vec![];
+
+        let mut denomination = Amount::from_msat(1);
+        while denomination < max {
+            amounts.push(denomination);
+            denomination = denomination * 2;
+        }
```
Comment (elsirion) [inline fedimint-server/src/config.rs:412]: Good use case for [`take_while`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.take_while).

```rust
(0..64).map(|power| Amount::from_msat(1u64 << power))
    .take_while(|&amt| amt < max)
    .collect()
```

**Review by elsirion — DISMISSED** [review]
LGTM, minor nits, feel free to merge :)

**Review by dpc — APPROVED** [review]

File: fedimint-server/src/config.rs (hunk 1 above)
Comment (jkitman) [reply fedimint-server/src/config.rs:412]: Kind of an unnecessary optimization though and wouldn't work with other powers.

**Review by elsirion — APPROVED** [review]
