### PR TITLE
fix(mint-client): detect gaps in nonce indices when repairing wallet

### LINKED ISSUE #7863: Allow gap limit in wallet repair

### PR DESCRIPTION
**Pull request by elsirion**
Fixes #7863

### CODE REVIEW

File: modules/fedimint-mint-client/src/repair_wallet.rs [hunk 1]
```diff
@@ -147,4 +137,30 @@ impl MintClientModule {
         dbtx.commit_tx().await;
         Ok(summary)
     }
+
+    /// Checks up to `gap_limit` nonces starting from `base_index` for having
+    /// being used already. If
+    async fn nonces_till_next_used(
```
Comment (dpc) [inline modules/fedimint-mint-client/src/repair_wallet.rs]: I'm confused about naming usage. If it returns `gap`, shouldn't it be called `gap_till_next_nonce_used` or something?

Also comment seems finished midsentence.

Comment (elsirion) [reply modules/fedimint-mint-client/src/repair_wallet.rs]: Yep, renamed and extended the sentence to a full one.

File: modules/fedimint-mint-client/src/repair_wallet.rs [hunk 2]
```diff
@@ -98,24 +99,18 @@ impl MintClientModule {
...
-                            "checking if blind nonce was already used",
-                            aggressive_backoff(),
-                            || async {
-                                Ok(module_api_inner.check_blind_nonce_used(blind_nonce).await?)
-                            },
-                        )
-                        .await?;
-
-                        if nonce_used {
+                        let nonces_used = self
```
Comment (dpc) [inline modules/fedimint-mint-client/src/repair_wallet.rs]: Nit: would rename this var too. `gap_till_next_nonce_used -> nonces_used -> gap` is weird, and "gap" is "nonces_unused" anyway.

Comment (elsirion) [reply modules/fedimint-mint-client/src/repair_wallet.rs]: I call it `maybe_nonce_gap` now

**Review by dpc — APPROVED** [review]
