### PR TITLE
fix: remove use of system time in ln client

### LINKED ISSUE #4363: Backport PR `#4356`
The backport bot was unable to open a pull request to backport changes from PR #4356. Please open a PR to backport these changes.

### PR DESCRIPTION
**Pull request by benthecarman**
Closes #4363

### CODE REVIEW

**Review by dpc — DISMISSED** [review]

File: modules/fedimint-ln-client/src/lib.rs [hunk 1]
```diff
@@ -903,7 +904,8 @@ impl LightningClientModule {
             .get_value(&MetaOverridesKey {})
             .await
         {
-            if meta.fetched_at.elapsed().unwrap() < META_OVERRIDE_CACHE_DURATION {
+            let elapsed = now().duration_since(meta.fetched_at).unwrap();
```
Comment (dpc) [inline modules/fedimint-ln-client/src/lib.rs:907]: BTW. We should have probably write a either a free-standing `elapsed` function in `fedimint_core` (just like `now`), or even use an extension trait.

Comment (m1sterc001guy) [inline modules/fedimint-ln-client/src/lib.rs:907]: Let's remove the `unwrap` here too and replace with `expect`

Comment (benthecarman) [reply modules/fedimint-ln-client/src/lib.rs]: done

File: modules/fedimint-ln-client/src/lib.rs [hunk 2]
```diff
@@ -903,7 +904,10 @@ impl LightningClientModule {
             .get_value(&MetaOverridesKey {})
             .await
         {
-            if meta.fetched_at.elapsed().unwrap() < META_OVERRIDE_CACHE_DURATION {
+            let elapsed = now()
+                .duration_since(meta.fetched_at)
+                .expect("time is always increasing");
```
Comment (elsirion) [inline modules/fedimint-ln-client/src/lib.rs:909]: That is not technically correct for `SystemTime`:

Screenshot 2024-02-20 at 20-05-21 SystemTime in std time - Rust

Maybe an `unwrap_or` would be better?

Comment (benthecarman) [reply modules/fedimint-ln-client/src/lib.rs]: Did `unwrap_or(0)` so it'll just refetch

**Review by dpc — APPROVED** [review]

File: modules/fedimint-ln-client/src/lib.rs (hunk 1 above)
Comment (bradleystachurski) [reply modules/fedimint-ln-client/src/lib.rs]: Good point 👍 

Tracking in https://github.com/fedimint/fedimint/issues/4383

File: modules/fedimint-ln-client/src/lib.rs (hunk 2 above)
Comment (bradleystachurski) [reply modules/fedimint-ln-client/src/lib.rs]: I believe `unwrap_or(0)` (or `unwrap_or_default` in merged diff) will return from the cache instead of refetching. I think either works, but want to highlight incase you specifically wanted the behavior to refetch.
