### PR TITLE
Fixes peg-out being under dust limit

### LINKED ISSUE #1693: Check peg-out tx validity
When generating a transaction for a peg-out we should check if bitcoind accepts it. Currently we dont prevent user generated dust outputs for example.

### PR DESCRIPTION
**Pull request by jkitman**
Simple fix for the dust limit error.

Fixes #1693 at least for this case, not sure whether we can generalize, especially given different bitcoin rpc backends.

### CODE REVIEW

File: modules/fedimint-wallet/src/lib.rs [hunk 1]
```diff
@@ -193,9 +193,9 @@ impl Serialize for UnsignedTransaction {
 }
 
 struct StatelessWallet<'a> {
-    descriptor: &'a Descriptor<CompressedPublicKey>,
-    secret_key: &'a secp256k1::SecretKey,
-    secp: &'a secp256k1::Secp256k1<secp256k1::All>,
+    pub descriptor: &'a Descriptor<CompressedPublicKey>,
+    pub secret_key: &'a secp256k1::SecretKey,
+    pub secp: &'a secp256k1::Secp256k1<secp256k1::All>,
```
Comment (elsirion) [inline modules/fedimint-wallet/src/lib.rs:198]: Why do these need to be pub? (not that we'd have great pub hygiene elsewhere, but would be nice to become more restrictive over time to reduce public APIs we are committed to)

**Review by elsirion — APPROVED** [review]

File: modules/fedimint-wallet/src/lib.rs (hunk 1 above)
Comment (jkitman) [reply modules/fedimint-wallet/src/lib.rs:198]: To be constructed in the `mod tests`.  Is there a better way around this?

Comment (elsirion) [reply modules/fedimint-wallet/src/lib.rs:198]: Can't submodules always access private fields of structs in super? Maybe I'm completely off here.

Comment (dpc) [reply modules/fedimint-wallet/src/lib.rs:198]: They should, AFAIK.

There's also `pub(crate)` and for integration tests we can always make some "hidden constructor" `#[doc(hidden)]` to cheat, yet not expose publicly stuff we don't want as a stable API.

**Review by dpc — APPROVED** [review]

File: modules/fedimint-wallet/src/lib.rs (hunk 1 above)
Comment (jkitman) [reply modules/fedimint-wallet/src/lib.rs]: Ah you are right, not sure why I got a compile error earlier.

**Review by elsirion — APPROVED** [review]
