### PR TITLE
fix: handle peer names with special chars

### LINKED ISSUE #2074: Replace invalid chars in peer_name with '_'
Right now, peer names with invalid TLS domain chars will cause failures.  It's a better user experience just to replace them with valid chars.

### PR DESCRIPTION
**Pull request by jkitman**
Fixes  #2074

@SumantxD took a shot at fixing it, using your string replacement code

### CODE REVIEW

**Comment by m1sterc001guy** [comment]
Are peer names used anywhere else besides the TLS cert? Only worry with silently replacing the bad characters with _ is if the user actually needs to use the peer name somewhere else, but now it's not what they expect.

**Review by m1sterc001guy — APPROVED** [review]

File: fedimint-bin-tests/src/federation.rs [hunk 1]
```diff
@@ -185,7 +185,7 @@ pub async fn run_dkg(root_task_group: &TaskGroup, servers: usize) -> anyhow::Res
     async fn create_tls(id: usize, sender: Sender<String>) -> anyhow::Result<()> {
         // set env vars
         let bin_dir = env::var("FM_BIN_DIR")?;
-        let server_name = format!("Server-{id}");
+        let server_name = format!("Server {id}!");
```
Comment (dpc) [inline fedimint-bin-tests/src/federation.rs:188]: I wonder if we should just

```
 info!(peer-id=peer_id, out-dir=out_dir", "creating TLS certs created for peer in {out_dir}");
```

kind of thing, instead of interpolating strings for logging.

Comment (jkitman) [reply fedimint-bin-tests/src/federation.rs:188]: Isn't this being used as a cmd line arg, not logging?

**Comment by jkitman** [comment]
> Are peer names used anywhere else besides the TLS cert? 

They are only replaced when used as a cert, otherwise they will be kept original everywhere else.  We just use the peer name in the TLS cert arbitrarily, it could be anything.

File: fedimint-bin-tests/src/federation.rs (hunk 1 above)
Comment (elsirion) [reply fedimint-bin-tests/src/federation.rs:188]: I don't understand that nit either, looks good to me, just test code running the dkg.

**Review by elsirion — APPROVED** [review]
We pin certs to peers, so actually don't care about domain names, otherwise we'd need to be careful with collisions here.

**Comment by jkitman** [comment]
> otherwise we'd need to be careful with collisions here

@elsirion Certs are pinned to the P2P endpoint in config gen, shouldn't that be enough?
