### PR TITLE
Backport: fix: deposit `Claimed` state waits for e-cash to be in wallet

### LINKED ISSUE #5942: Backport PR `#5933` fix: deposit `Claimed` state waits for e...
PR: #5933
Title: fix: deposit `Claimed` state waits for e-cash to be in wallet

The backport bot failed. Please open a PR to backport these changes.

### PR DESCRIPTION
**Pull request by elsirion**
Fixes  #5942

### CODE REVIEW

File: modules/fedimint-wallet-client/src/lib.rs [hunk 1]
```diff
@@ -864,18 +869,25 @@ impl WalletClientModule {
...
+                };
+
+                match stream_cient_ctx.await_primary_module_outputs(operation_id, claim_data.change).await {
+                    Ok(_) =>yield DepositStateV2::Claimed {
                         btc_deposited,
-                        btc_out_point,
-                    };
+                        btc_out_point},
+                    Err(e) => yield DepositStateV2::Failed(e.to_string())
+                    }
```
Comment (bradleystachurski) [inline modules/fedimint-wallet-client/src/lib.rs:890]: [nit] The formatting is a bit off

**Review by bradleystachurski — APPROVED** [review]

File: modules/fedimint-wallet-client/src/lib.rs (hunk 1 above)
Comment (elsirion) [reply modules/fedimint-wallet-client/src/lib.rs]: good catch!

Comment (elsirion) [reply modules/fedimint-wallet-client/src/lib.rs]: Macro formatting is a bit broken in my IDE unfortunately :/

**Review by bradleystachurski — APPROVED** [review]
