### PR TITLE
fix(client): fetch api announcements on join

### LINKED ISSUE #6976: Joining federation with all API URLs overridden fails
When joining a new federation where all API URLs have been overridden the client should use the URL from the join code to fetch API announcements before starting the client.

### PR DESCRIPTION
**Pull request by dpc**
Fix #6976

**Edit**: Argh, the whole thing does not work, because we already exposed federation_id hashing into secret to the outside of join, and for that client needs federation_id, and for that they need to download the config.

**Edit**: OK, fixed that, but... Argh, as we need to do more stuff on join, we can't have it repeated over and over everywhere, so we need to fold it into client.  But that doesn't work with preview ...

**Edit**: Well, I had to refactor even more things. :shrug: . But I kind of like this explicit preview step now.

### CODE REVIEW

File: fedimint-cli/src/lib.rs [hunk 1]
```diff
@@ -675,24 +675,16 @@ impl FedimintCli {
...
+        let mut client_builder = self.make_client_builder(cli).await?;
 
-        let client_builder = self.make_client_builder(cli).await?;
+        client_builder.with_connector(cli.connector());
 
         let mnemonic = load_or_generate_mnemonic(client_builder.db_no_decoders()).await?;
 
         let client = client_builder
-            .join(
-                get_default_client_secret(
```
Comment (dpc) [inline fedimint-cli/src/lib.rs:690]: Deriving the root secret using federation_id, also something that should be internal to `fedimint-client`.

File: fedimint-client/src/api_announcements.rs [hunk 2]
```diff
@@ -37,81 +38,111 @@ impl_db_lookup!(
 
 /// Fetches API URL announcements from guardians, validates them and updates the
 /// DB if any new more upt to date ones are found.
-pub async fn run_api_announcement_sync(client_inner: Arc<Client>) {
+pub(crate) async fn run_api_announcement_sync(client_inner: Arc<Client>) {
     // Wait for the guardian keys to be available
     let guardian_pub_keys = client_inner.get_guardian_public_keys_blocking().await;
     loop {
-        let results = join_all(client_inner.api.all_peers().iter()
```
Comment (dpc) [inline fedimint-client/src/api_announcements.rs:44]: Had to split this blob into separate steps, so I can reuse them.

File: fedimint-client/src/api_announcements.rs [hunk 3]
```diff
@@ -37,81 +38,111 @@ impl_db_lookup!(
...
+            }
+            Err(e) => {
                 warn!(target: LOG_CLIENT, %peer_id, ?e, "Failed to process API announcements");
             }
         }
+    }
 
-        // Check once an hour if there are new announcements
-        sleep(Duration::from_secs(3600)).await;
+    if some_success {
```
Comment (dpc) [inline fedimint-client/src/api_announcements.rs:75]: If we at least got success from a single peer, we should consider that enough (success).

File: fedimint-client/src/client/builder.rs [hunk 4]
```diff
@@ -394,16 +397,54 @@ impl ClientBuilder {
...
+                config.clone(),
+                invite_code.api_secret(),
+                InitMode::Fresh,
+            )
+            .await?;
+
+        Ok(client)
+    }
+
+    pub async fn join_with_existing_config(
```
Comment (dpc) [inline fedimint-client/src/client/builder.rs:434]: One of the testing thingies needed this version, so I let it have it.

**Comment by dpc** [comment]
Huh. I guess I broke cli tests. Weird because they passed locally, but I hope I can repro.

**Comment by dpc** [comment]
@maan2003 Would be great to know what do you think about the preview thing in particular.

File: fedimint-client/src/client/builder.rs [hunk 5]
```diff
@@ -55,6 +58,51 @@ use crate::oplog::OperationLog;
...
+    /// Only use a single internal federation-id hashing.
+    ///
+    /// Use this method if you are building a new application, that
+    /// did not use old system in the past, and save yourself some trouble.
+    ///
+    /// The high level application is free to re-use the same secret for
+    /// multiple different federations. Or not. But client APIs will not
+    /// expose federation_id to the outside before join/recover operations.
+    Standard(DerivableSecret),
+}
```
[the remark this answers is not in the document]
Comment (dpc) [reply fedimint-client/src/client/builder.rs:94]: I think I need to introduce something like `RootSecret` even if just to bring to the developer attention that the derivation will happen internally now, so they don't need to do it.

Now ... Do we really need a `Standard` variant... I'm not sure. Seems to me like this double derive is clunky and gets in the way. And compatibility between different clients is unnecessary, and possibly even harmful as different clients will have different seed reuse protections, most probably incompatible, so more people will burn themselves with it, than it will help.

But it could be removed.

**Comment by elsirion** [comment]
MQ failure was just a cachix issue
