### PR TITLE
Fix slow external LN payments. Fixes #603

### LINKED ISSUE #603: Slow LN payments
I noticed a performance regression on signet that LN routed payments take ~15s. It seems I introduced that in #533 myself by using a function that retries fetching a hypothetical offer till a timeout is hit instead of just checking once and continuing.

### PR DESCRIPTION
**Pull request by elsirion**
> I noticed a performance regression on signet that LN routed payments take ~15s. It seems I introduced that in https://github.com/fedimint/fedimint/pull/533 myself by using a function that retries fetching a hypothetical offer till a timeout is hit instead of just checking once and continuing.

### CODE REVIEW

**Comment by elsirion** [comment]
I deployed it to the signet with https://github.com/elsirion/fedimint-signet/commit/ca4fde50c859ebe81cb20bc5a423c7adb001878d

File: client/client-lib/src/api.rs [hunk 1]
```diff
@@ -55,6 +55,10 @@ pub trait FederationApi: Send + Sync {
     /// Fetch preimage offer for incoming lightning payments
     async fn fetch_offer(&self, payment_hash: Sha256Hash) -> Result<IncomingContractOffer>;
 
+    // TODO: find a better abstraction for all our API endpoints that allows different strategies and timeouts
+    /// Checks if there exists an offer for a payment hash
+    async fn offer_exists(&self, payment_hash: Sha256Hash) -> Result<bool>;
```
Comment (dpc) [inline client/client-lib/src/api.rs:60]: Is the end goal for this to be a some kind of general method for all server modules, or would this be better served as a private endpoint specific to ln module?

Comment (elsirion) [reply client/client-lib/src/api.rs:60]: In a modularized future that would be an API endpoint specific to the LN module. But currently everything lives in `FederationApi`.

Comment (dpc) [reply client/client-lib/src/api.rs:60]:
```
fn api_endpoints(&self) -> &'static [ApiEndpoint<Self>]
```

What about this one on `FederationApi`?

Comment (elsirion) [reply client/client-lib/src/api.rs:60]: That's on the server side to register module endpoints with the federation's API server.

File: ln-gateway/src/lib.rs [hunk 2]
```diff
@@ -183,22 +181,20 @@ impl LnGateway {
...
+            && self
+                .federation_client
+                .ln_client()
+                .offer_exists(payment_params.payment_hash)
+                .await
+                .unwrap_or(false);
+
+        let preimage_res = if is_internal_payment {
+            self.buy_preimage_internal(&payment_params, &mut rng).await
+        } else {
```
Comment (okjodom) [inline ln-gateway/src/lib.rs:194]: This rolls back fallback behavior. Do we want to mark it with an issue so we can reintroduce fallback later?

**Review by okjodom — APPROVED** [review]

File: ln-gateway/src/lib.rs (hunk 2 above)
Comment (elsirion) [reply ln-gateway/src/lib.rs:194]: It doesn't because we check if a preimage is for sale before deciding if we should route internally or externally:

```rust
        let is_internal_payment = payment_params.maybe_internal
            && self
                .federation_client
                .ln_client()
                .offer_exists(payment_params.payment_hash)
                .await
                .unwrap_or(false);
```

This wastes one API call in the internal routing case but was better than rearchitecting the entire API client imo.

Comment (okjodom) [reply ln-gateway/src/lib.rs:194]: Oh nice. This addresses the private channel case which would look like an internal payment from route hint inspection

**Review by dpc — APPROVED** [review]
