### PR TITLE
Claim a refund if gateway fails to decrypt preimage from offer

### LINKED ISSUE #532: Internal payments: Gateways should claim a refund if they fail to decrypt offer preimage
When routing internal payments, Gateways can run into a state where they have bought an offer but cannot decrypt the preimage in order to proceed with completion of the matching outgoing contract.

The gateway should ensure to fairly claim a refund to avoid making a loss

### PR DESCRIPTION
**Pull request by okjodom**
When handling internal payments, the gateways should claim a refund if it fails the preimage obtained from buying offer
Closes #532 

- [x] WIP: tests

### CODE REVIEW

File: ln-gateway/src/lib.rs [hunk 1]
```diff
@@ -222,19 +222,32 @@ impl LnGateway {
...
+        {
+            Ok(preimage) => {
+                debug!("Decrypted preimage {:?}", preimage);
+                Ok(preimage.0.serialize())
+            }
+            Err(e) => {
+                warn!("Failed to decrypt preimage. Now requesting a refund: {}", e);
+                self.federation_client
+                    .refund_incoming_contract(contract_id, rng)
+                    .await?;
```
Comment (NicolaLS) [inline ln-gateway/src/lib.rs:247]: returning an error from `refund_incoming_contract` contract could be confusing but I don't know what to do about that

Comment (elsirion) [reply ln-gateway/src/lib.rs:247]: Maybe we can map the error into something with more context?

**Review by elsirion — APPROVED** [review]
Looks good, tests would be nice though :)

**Comment by okjodom** [comment]
> tests would be nice though :)

Lol it was really easy to trigger the refund scenario by failing to run some epochs, in `test:lightning_gateway_pays_internal_invoice`. Good for manual testing. But far harder to clean up and submit as a new test case.

Now, a timeout in preimage decryption is just one scenario for hitting a refund case. I'd actually want to build on @NicolaLS revised test fixtures to simulate both preimage decryption timeout and "invalid preimage" failure reasons, leading to claiming of refund

File: integrationtests/tests/tests.rs [hunk 2]
```diff
@@ -453,6 +453,71 @@ async fn lightning_gateway_pays_outgoing_invoice() {
...
+        .await_outgoing_contract_acceptance(funding_outpoint)
+        .await
+        .unwrap();
+    debug!("Outgoing contract accepted");
+
+    let response = tokio::join!(gateway.server.pay_invoice(contract_id, rng()), async {
+        // we should run 4 epocks to buy preimage from offer, decrypt preimage, claim outgoing contract, mint the tokens
+        // but we only run 1 epoch to simulate timeout in preimage decryption
+        // This results in an error and the gateway reclaims funds used to buy preimage
+        fed.await_consensus_epochs(1).await;
```
Comment (okjodom) [inline integrationtests/tests/tests.rs:510]: Manual assertion based on this simulation is okay, but it's not nice that I can't yet write  assertions for the same outcome given the possible fail reasons. Marking with a TODO.

PS, Would it be easier to test this level of detail in a scoped integration test between GW and mocked out Fedimint? Not sure if Issue #545 is tending towards such a possibility

**Comment by elsirion** [comment]
> I'd actually want to build on @NicolaLS revised test fixtures to simulate both preimage decryption timeout and "invalid preimage" failure reasons

Can we do this in another PR? Would like to get this one in :)

**Review by elsirion — APPROVED** [review]
