### PR TITLE
fix(recurringd): avoid "holes" in invoice indices getting sync stuck

### LINKED ISSUE #7650: Atomicity bug in `recurringd`: invoice indices are being skipped
Somehow it seems users can trigger the skipping of invoice indices, resulting in the client getting stuck syncing.

### PR DESCRIPTION
**Pull request by elsirion**
The main fix was choosing and incrementing the invoice index in the same database transaction as saving the generated invoice. But since we unfortunately can't also generate the invoice in the same dbtx some more work was required.

In the old code, aborting the function would result in an unused index, the problem with that was that the client always checks for the next index and if none is present assumes no further invoices have been generated. This obviously breaks in the presence of skipped indices.

In the new model the failure mode is changed: we'll never skip an index, but rather generate two invoices with the same index if not careful (since the invoice is still generated using a separate dbtx). This would result in trying to add a second operation with the same operation id, causing a panic. To avoid this the code now checks if there was an aborted call to the `create_bolt11_invoice` function and repairs the DB if so, only then it generates the actually requested invoice.

Fixes #7650.

### CODE REVIEW

File: fedimint-recurringd/src/lib.rs [hunk 1]
```diff
@@ -257,44 +261,122 @@ impl RecurringInvoiceServer {
...
+                            PaymentCodeVariant::Lnurl { meta } => meta,
+                        };
+                        let meta_hash = Sha256(sha256::Hash::hash(lnurl_meta.as_bytes()));
+                        let description = Bolt11InvoiceDescription::Hash(meta_hash);
+
+                        // TODO: ideally creating the invoice would take a dbtx as argument so we
+                        // don't have to do the "check if invoice already exists" dance
+                        let (operation_id, invoice, _preimage) = federation_client_ln_module
+                            .create_bolt11_invoice_for_user_tweaked(
+                                amount,
```
Comment (elsirion) [inline fedimint-recurringd/src/lib.rs:340]: Doesn't look that hard after all, let's do that
