### PR TITLE
fix(ln-client): verify operation type when subscribing to LN payment updates

### LINKED ISSUE #6000: Panic in LN update stream
A user hit this panic in the wild:

https://github.com/fedimint/fedimint/blob/6e552f42657474325cc4b4980d21e577adbd5fd1/modules/fedimint-ln-client/src/lib.rs#L1223-L1231

It's unclear to me why there'd suddenly be a state that isn't expected (we check that we are dealing with the correct operation kind earlier), but fundamentally we should likely not panic on non-critical client programmer errors. Logging an error and returning none would be better here imo.

I still think that panics are great for critical code paths where broken invariants can cause loss of funds, but e.g. update streams are purely informational and inconsistencies are preferable to crashing the whole application.

### PR DESCRIPTION
**Pull request by elsirion**
Fixes #6000

### CODE REVIEW

File: modules/fedimint-ln-client/src/lib.rs [hunk 1]
```diff
@@ -1185,6 +1185,23 @@ impl LightningClientModule {
         operation_id: OperationId,
     ) -> anyhow::Result<UpdateStreamOrOutcome<InternalPayState>> {
         let operation = self.client_ctx.get_operation(operation_id).await?;
+
+        let LightningOperationMetaVariant::Pay(LightningOperationMetaPay {
+            out_point: _,
+            invoice: _,
+            change: _, // FIXME: why isn't this used here?
```
Comment (m1sterc001guy) [inline modules/fedimint-ln-client/src/lib.rs:1192]: I believe the outpoint for this isn't used because it is passed through the `RefundSubmitted` state.

**Review by m1sterc001guy — APPROVED** [review]

**Comment by elsirion** [comment]
This lead to quite some pain, so possibly worth backporting if it applies cleanly.

**Comment by fedimint-backports** [comment]
Successfully created backport PR for `releases/v0.4`:
- #6046
