### PR TITLE
Fix WebsocketSecure connections on Android

### LINKED ISSUE #589: Websocket Secure (`wss://...`) doesn't work on Android
This is the root issue https://github.com/paritytech/subxt/issues/563

Assigning this to you @elsirion

### PR DESCRIPTION
**Pull request by justinmoon**
Closes #589

### CODE REVIEW

File: client/client-lib/src/api.rs [hunk 1]
```diff
@@ -287,6 +289,14 @@ pub trait JsonRpcClient: ClientT + Sized {
...
 impl JsonRpcClient for WsClient {
     async fn connect(url: &Url) -> std::result::Result<Self, JsonRpcError> {
+        // rustls-native-certs doesn't support android
+        #[cfg(target_os = "android")]
+        return WsClientBuilder::default()
+            .certificate_store(CertificateStore::WebPki)
+            .build(url_to_string_with_default_port(url)) // Hack for default ports, see fn docs
+            .await;
+
+        #[cfg(not(target_os = "android"))]
```
Comment (justinmoon) [inline client/client-lib/src/api.rs:299]: LMK if there's a more elegant way to do this

**Review by elsirion — APPROVED** [review]
