### PR TITLE
test: re-enable gateway swap balance assertion

### LINKED ISSUE #3679: Reactivate partially disabled intermittently failing gateway test
See #3675

### PR DESCRIPTION
**Pull request by okjodom**
asserting gateway balance after swap seems sensitive to consensus +  gateway state
 machine performance. this change adds a 5s sleep, hopefully giving the gateway a chance to claim
outgoing contract and update balances before we assert new balances

fixes #3679 
drafting this as a fix but we'd need correlation with latency test data from #3696

### CODE REVIEW

File: gateway/ln-gateway/tests/integration_tests.rs [hunk 1]
```diff
@@ -1184,17 +1184,16 @@ async fn test_gateway_executes_swaps_between_connected_federations() -> anyhow::
             assert_matches!(claimed, LnReceiveState::Claimed);
             assert_eq!(client2.get_balance().await, invoice_amt);
 
-            // FIXME: https://github.com/fedimint/fedimint/issues/3672
-            // This assertion intermittently fails and is a blocker on the CI pipeline
-            // we need to investigate further why the gateway balance may not be updating
-            //
+            // Give the gateway a chance to update it's balances
+            sleep(Duration::from_secs(5)).await;
```
Comment (justinmoon) [inline gateway/ln-gateway/tests/integration_tests.rs:1188]: You could speed this up by polling the balance for 5 seconds, and fail the test if it doesn't update in 5 seconds, but continue if it does.

**Review by justinmoon — DISMISSED** [review]

File: gateway/ln-gateway/tests/integration_tests.rs (hunk 1 above)
Comment (okjodom) [reply gateway/ln-gateway/tests/integration_tests.rs]: updated

found it non-intuitive that we have to do
```rs
if post_balances[0] == pre_balances[0] && post_balances[1] == pre_balances[1] { // error balances not updated }
```
and not
```rs
if post_balances == pre_balances { // error balances not updated }
```
because we are watching perf and latencies in two distinct federations

**Review by justinmoon — APPROVED** [review]

**Review by elsirion — APPROVED** [review]
