### PR TITLE
Fix wallet round consensus

### LINKED ISSUE #2011: Wallet round consensus multiple submissions bug
> Before throwing away the peer id, do we make sure that each peer only contributed one item? Otherwise malicious ones could take over. Needs to be fixed in wallet too.

_Originally posted by @elsirion in https://github.com/fedimint/fedimint/pull/1074#discussion_r1146335734_

### PR DESCRIPTION
**Pull request by jkitman**
Fixes #2011

### CODE REVIEW

File: modules/fedimint-wallet-server/src/lib.rs [hunk 1]
```diff
@@ -894,43 +861,51 @@ impl Wallet {
...
+            if dedup.insert(peer, item).is_some() {
+                warn!("Peer {} submitted multiple RoundConsensusItem", peer);
+            }
+        }
+        let items: Vec<_> = dedup.values().into_iter().collect();
 
-        let consensus_height = self.consensus_height(dbtx).await.unwrap_or(0);
+        let mut fees: Vec<_> = items.iter().map(|item| item.fee_rate).collect();
+        fees.sort_unstable();
+        let fee_rate = *fees.get(fees.len() / 2).expect("is non-empty");
```
Comment (m1sterc001guy) [inline modules/fedimint-wallet-server/src/lib.rs:890]: Nit: The error message on expect could be more informative here

File: modules/fedimint-wallet-server/src/lib.rs [hunk 2]
```diff
@@ -1582,12 +1557,61 @@ mod tests {
...
+        // removes duplicate entries for a given peer, keeping last entry
+        let consensus = Wallet::process_round_consensus(
+            0,
+            vec![
+                (PeerId::from(0), round_item(1, 4, 7)),
+                (PeerId::from(1), round_item(2, 5, 8)),
+                (PeerId::from(1), round_item(3, 6, 9)),
+            ],
+        );
+        assert_eq!(consensus, round_consensus(3, 6, 7 ^ 9));
```
Comment (m1sterc001guy) [inline modules/fedimint-wallet-server/src/lib.rs:1613]: For the block height and fees here, does the median calculation default to using a specific entry rather than averaging the numbers? (for instance, even when discounting Peer 1's first `RoundConsensusItem`, shouldn't the block height be an average of 1 and 3?)

Comment (jkitman) [reply modules/fedimint-wallet-server/src/lib.rs:1613]: It's a median, so you throw out the duplicate, divide the number of items by 2 (`2/2=1`) so you get the last item.

Comment (elsirion) [reply modules/fedimint-wallet-server/src/lib.rs:1613]: I think there are different definitions of medians, but this one was good enough when I thought it through.

File: modules/fedimint-wallet-server/Cargo.toml [hunk 3]
```diff
@@ -42,3 +42,4 @@ fedimint-server = { path = "../../fedimint-server" }
 fedimint-testing = { path = "../../fedimint-testing" }
 test-log = { version = "0.2", features = [ "trace" ], default-features = false }
 tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
+tokio = { version = "1.26.0", features = ["full"] }
```
[the remark this answers is not in the document]
Comment (jkitman) [reply modules/fedimint-wallet-server/Cargo.toml:45]: If you want run the tests only in that crate, they require tokio.

**Review by m1sterc001guy — APPROVED** [review]
LGTM
