### PR TITLE
fix: Add checks in Wallet to ensure Bitcoin is configured correctly

### LINKED ISSUE #1416: On start fedimint should check the bitcoin node
Maybe we could have

```
ModuleGen::check_env(/* the env vars we pass to modules*)
```

and call it on each module kind in `ModuleInitRegistry`

Then Wallet Module should try to make a `getblockcount`, check network and display this info, or print and error.

This would help a lot get a quick feedback even before setting up the federation.

### PR DESCRIPTION
**Pull request by asifshiraz**
Fixes #1416 and #1417

### CODE REVIEW

File: modules/fedimint-wallet/src/lib.rs [hunk 1]
```diff
@@ -975,6 +975,14 @@ impl Wallet {
             ));
         }
 
+        bitcoind_rpc.get_block_height().await.unwrap_or_else(|error| {
```
Comment (dpc) [inline modules/fedimint-wallet/src/lib.rs:978]: I would love to see `info!` when things go OK as well.

File: modules/fedimint-wallet/src/lib.rs [hunk 2]
```diff
@@ -975,6 +975,16 @@ impl Wallet {
             ));
         }
 
+        match bitcoind_rpc.get_block_height().await {
+            Ok(_) => info!("Bitcoin node verified successfully."),
```
Comment (dpc) [inline modules/fedimint-wallet/src/lib.rs:979]:
```
Ok(height) => info!(height, "Connected to bitcoind"),
```

?

File: modules/fedimint-wallet/src/lib.rs [hunk 3]
```diff
@@ -975,6 +975,16 @@ impl Wallet {
...
+            Err(err) => warn!("Bitcoin node is not ready or configured properly. Modules relying on it may not function correctly: {:?}", err),
+        }
+
+        match bitcoind_rpc.get_fee_rate(1).await {
+            Ok(_) => info!("Bitcoin fee estimation verified successfully"),
```
Comment (dpc) [inline modules/fedimint-wallet/src/lib.rs:984]:
```
Ok(feerate) => info!(feerate, "Bitcoind feerate available"),
```

?

**Review by dpc — DISMISSED** [review]

**Review by dpc — APPROVED** [review]

**Review by m1sterc001guy — DISMISSED** [review]

**Comment by dpc** [comment]
@elsirion 

```
info!(feerate = feerate.ok_or(0), "Bitcoind feerate available")
```

(might need `feerate = %feerate.ok_or(0)`)

**Review by dpc — DISMISSED** [review]

File: modules/fedimint-wallet/src/lib.rs [hunk 4]
```diff
@@ -970,6 +970,16 @@ impl Wallet {
             ));
         }
 
+        match bitcoind_rpc.get_block_height().await {
+            Ok(height) => info!(height, "Connected to bitcoind"),
+            Err(err) => warn!("Bitcoin node is not ready or configured properly. Modules relying on it may not function correctly: {:?}", err),
+        }
+
+        match bitcoind_rpc.get_fee_rate(1).await {
+            Ok(feerate) => info!(feerate = feerate.ok_or(0), "Bitcoind feerate available"),
```
Comment (dpc) [inline modules/fedimint-wallet/src/lib.rs:979]:
```
 fedimint-workspace-build> 979 |             Ok(feerate) => info!(feerate = feerate.ok_or(0), "Bitcoind feerate available"),
```

Weird. Maybe `feerate = ( ... )` is needed etc. Or just `match` again or something.

Comment (asifshiraz) [reply modules/fedimint-wallet/src/lib.rs]: It was complaining that tracing::Value trait is not implemented by Feerate. I couldn't figure out how to do that. Since there is only one property in Feerate struct, I thought we can output that in the logs for now, and then revisit how to enable tracing by implementing the relevant tracing traits, if that is the right way to go about it.

**Review by dpc — APPROVED** [review]

**Review by jkitman — APPROVED** [review]

**Review by elsirion — APPROVED** [review]
We should talk about making the warning stronger since this will currently stall the federation afaik? But a good first start!
