### PR TITLE
fix(devimint): off-by-one error for mempool transactions

### LINKED ISSUE #3884: Investigate `generate_epochs` off by one error
Originally flagged in https://github.com/fedimint/fedimint/pull/3865#discussion_r1420478352

- Find off-by-one root cause
- Consider rename for `generate_epochs`

### PR DESCRIPTION
**Pull request by bradleystachurski**
Fixes #3884

- Add helper to mine enough blocks to finalize mempool transactions
- Remove `generate_epochs` since epochs are no longer part of consensus

### CODE REVIEW

File: devimint/src/federation.rs [hunk 1]
```diff
@@ -219,20 +219,17 @@ impl Federation {
 
     pub async fn await_block_sync(&self) -> Result<u64> {
         let finality_delay = self.get_finality_delay().await?;
-        let bitcoind_block_count = self.bitcoind.client().get_blockchain_info()?.blocks;
-        let expected = bitcoind_block_count.saturating_sub(finality_delay.into());
+        // Fedimint's IBitcoindRpc considers block count the total number of blocks,
+        // where bitcoind's rpc returns the height. Since the genesis block has height
+        // 0, we need to add 1 to get the total block count.
+        let block_count = self.bitcoind.client().get_block_count()? + 1;
```
Comment (dpc) [inline devimint/src/federation.rs:225]: **suggestion:** Could we just do `get_block_count` on `Bitcoind` itself and put the adjustment there?

**Review by dpc — APPROVED** [review]

File: devimint/src/federation.rs (hunk 1 above)
Comment (bradleystachurski) [reply devimint/src/federation.rs:225]: Ahh yep, that's a good improvement :+1: 

https://github.com/fedimint/fedimint/pull/3898
